/*
 * Java bean class for entity table t_loan 
 * Created on 17 ËÄÔÂ 2013 ( Time 21:58:36 )
 * Generated by Telosys Tools Generator ( version 2.0.3 )
 */

package com.hlj.tech.kdkj.customer.entities ;

import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Entity bean for table "t_loan"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TLoan implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    loanId       ; // Primary Key

    private Integer    customerPid  ;
    private String     username     ;
    private BigDecimal loanLimit    ;
    private Integer    loanMonth    ;
    private String     loanReturntype ;
    private String     loanUsage    ;
    private Date       loanOpentime ;
    private String     bankAccount  ;
    private String     bankAccountno ;
    private String     bankOpenname ;
    private String     bankType     ;
    private String     loanBigtype  ;
    private String     loanSmalltype ;
    private String     state        ;
    private Byte       success      ;
    private String     successState ;
    private Date       createDate   ;
    private Date       updateDate   ;
    private Byte       multiBorrower ;
    private String     loanGennumber ;
    private TLoanHouse tLoanHouse  ;
    private List<TSpousefriend> listOfTSpousefriend;
    private List<TLoanConsult> listOfTLoanConsult;
    private TCustomer  tCustomer   ;
    private TLoanVechicle tLoanVechicle;
    private TLoanBoss  tLoanBoss   ;
    /**
     * Default constructor
     */
    public TLoan()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "loanId" field value
     * This field is mapped on the database column "loan_id" ( type "int", ) 
     * @param loanId
     */
	public void setLoanId( Integer loanId )
    {
        this.loanId = loanId ;
    }
    /**
     * Get the "loanId" field value
     * This field is mapped on the database column "loan_id" ( type "int", ) 
     * @return the field value
     */
	public Integer getLoanId()
    {
        return this.loanId;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : customer_pid ( int ) 
    /**
     * Set the "customerPid" field value
     * This field is mapped on the database column "customer_pid" ( type "int" ) 
     * @param customerPid
     */
    public void setCustomerPid( Integer customerPid )
    {
        this.customerPid = customerPid;
    }
    /**
     * Get the "customerPid" field value
     * This field is mapped on the database column "customer_pid" ( type "int" ) 
     * @return the field value
     */
    public Integer getCustomerPid()
    {
        return this.customerPid;
    }

    //--- DATABASE MAPPING : userName_ ( varchar ) 
    /**
     * Set the "username" field value
     * This field is mapped on the database column "userName_" ( type "varchar" ) 
     * @param username
     */
    public void setUsername( String username )
    {
        this.username = username;
    }
    /**
     * Get the "username" field value
     * This field is mapped on the database column "userName_" ( type "varchar" ) 
     * @return the field value
     */
    public String getUsername()
    {
        return this.username;
    }

    //--- DATABASE MAPPING : loan_limit ( decimal ) 
    /**
     * Set the "loanLimit" field value
     * This field is mapped on the database column "loan_limit" ( type "decimal" ) 
     * @param loanLimit
     */
    public void setLoanLimit( BigDecimal loanLimit )
    {
        this.loanLimit = loanLimit;
    }
    /**
     * Get the "loanLimit" field value
     * This field is mapped on the database column "loan_limit" ( type "decimal" ) 
     * @return the field value
     */
    public BigDecimal getLoanLimit()
    {
        return this.loanLimit;
    }

    //--- DATABASE MAPPING : loan_month ( int ) 
    /**
     * Set the "loanMonth" field value
     * This field is mapped on the database column "loan_month" ( type "int" ) 
     * @param loanMonth
     */
    public void setLoanMonth( Integer loanMonth )
    {
        this.loanMonth = loanMonth;
    }
    /**
     * Get the "loanMonth" field value
     * This field is mapped on the database column "loan_month" ( type "int" ) 
     * @return the field value
     */
    public Integer getLoanMonth()
    {
        return this.loanMonth;
    }

    //--- DATABASE MAPPING : loan_returnType ( varchar ) 
    /**
     * Set the "loanReturntype" field value
     * This field is mapped on the database column "loan_returnType" ( type "varchar" ) 
     * @param loanReturntype
     */
    public void setLoanReturntype( String loanReturntype )
    {
        this.loanReturntype = loanReturntype;
    }
    /**
     * Get the "loanReturntype" field value
     * This field is mapped on the database column "loan_returnType" ( type "varchar" ) 
     * @return the field value
     */
    public String getLoanReturntype()
    {
        return this.loanReturntype;
    }

    //--- DATABASE MAPPING : loan_usage ( varchar ) 
    /**
     * Set the "loanUsage" field value
     * This field is mapped on the database column "loan_usage" ( type "varchar" ) 
     * @param loanUsage
     */
    public void setLoanUsage( String loanUsage )
    {
        this.loanUsage = loanUsage;
    }
    /**
     * Get the "loanUsage" field value
     * This field is mapped on the database column "loan_usage" ( type "varchar" ) 
     * @return the field value
     */
    public String getLoanUsage()
    {
        return this.loanUsage;
    }

    //--- DATABASE MAPPING : loan_openTime ( date ) 
    /**
     * Set the "loanOpentime" field value
     * This field is mapped on the database column "loan_openTime" ( type "date" ) 
     * @param loanOpentime
     */
    public void setLoanOpentime( Date loanOpentime )
    {
        this.loanOpentime = loanOpentime;
    }
    /**
     * Get the "loanOpentime" field value
     * This field is mapped on the database column "loan_openTime" ( type "date" ) 
     * @return the field value
     */
    public Date getLoanOpentime()
    {
        return this.loanOpentime;
    }

    //--- DATABASE MAPPING : bank_account ( varchar ) 
    /**
     * Set the "bankAccount" field value
     * This field is mapped on the database column "bank_account" ( type "varchar" ) 
     * @param bankAccount
     */
    public void setBankAccount( String bankAccount )
    {
        this.bankAccount = bankAccount;
    }
    /**
     * Get the "bankAccount" field value
     * This field is mapped on the database column "bank_account" ( type "varchar" ) 
     * @return the field value
     */
    public String getBankAccount()
    {
        return this.bankAccount;
    }

    //--- DATABASE MAPPING : bank_accountNo ( varchar ) 
    /**
     * Set the "bankAccountno" field value
     * This field is mapped on the database column "bank_accountNo" ( type "varchar" ) 
     * @param bankAccountno
     */
    public void setBankAccountno( String bankAccountno )
    {
        this.bankAccountno = bankAccountno;
    }
    /**
     * Get the "bankAccountno" field value
     * This field is mapped on the database column "bank_accountNo" ( type "varchar" ) 
     * @return the field value
     */
    public String getBankAccountno()
    {
        return this.bankAccountno;
    }

    //--- DATABASE MAPPING : bank_openName ( varchar ) 
    /**
     * Set the "bankOpenname" field value
     * This field is mapped on the database column "bank_openName" ( type "varchar" ) 
     * @param bankOpenname
     */
    public void setBankOpenname( String bankOpenname )
    {
        this.bankOpenname = bankOpenname;
    }
    /**
     * Get the "bankOpenname" field value
     * This field is mapped on the database column "bank_openName" ( type "varchar" ) 
     * @return the field value
     */
    public String getBankOpenname()
    {
        return this.bankOpenname;
    }

    //--- DATABASE MAPPING : bank_type ( varchar ) 
    /**
     * Set the "bankType" field value
     * This field is mapped on the database column "bank_type" ( type "varchar" ) 
     * @param bankType
     */
    public void setBankType( String bankType )
    {
        this.bankType = bankType;
    }
    /**
     * Get the "bankType" field value
     * This field is mapped on the database column "bank_type" ( type "varchar" ) 
     * @return the field value
     */
    public String getBankType()
    {
        return this.bankType;
    }

    //--- DATABASE MAPPING : loan_bigType ( varchar ) 
    /**
     * Set the "loanBigtype" field value
     * This field is mapped on the database column "loan_bigType" ( type "varchar" ) 
     * @param loanBigtype
     */
    public void setLoanBigtype( String loanBigtype )
    {
        this.loanBigtype = loanBigtype;
    }
    /**
     * Get the "loanBigtype" field value
     * This field is mapped on the database column "loan_bigType" ( type "varchar" ) 
     * @return the field value
     */
    public String getLoanBigtype()
    {
        return this.loanBigtype;
    }

    //--- DATABASE MAPPING : loan_smallType ( varchar ) 
    /**
     * Set the "loanSmalltype" field value
     * This field is mapped on the database column "loan_smallType" ( type "varchar" ) 
     * @param loanSmalltype
     */
    public void setLoanSmalltype( String loanSmalltype )
    {
        this.loanSmalltype = loanSmalltype;
    }
    /**
     * Get the "loanSmalltype" field value
     * This field is mapped on the database column "loan_smallType" ( type "varchar" ) 
     * @return the field value
     */
    public String getLoanSmalltype()
    {
        return this.loanSmalltype;
    }

    //--- DATABASE MAPPING : state ( varchar ) 
    /**
     * Set the "state" field value
     * This field is mapped on the database column "state" ( type "varchar" ) 
     * @param state
     */
    public void setState( String state )
    {
        this.state = state;
    }
    /**
     * Get the "state" field value
     * This field is mapped on the database column "state" ( type "varchar" ) 
     * @return the field value
     */
    public String getState()
    {
        return this.state;
    }

    //--- DATABASE MAPPING : success ( tinyint ) 
    /**
     * Set the "success" field value
     * This field is mapped on the database column "success" ( type "tinyint" ) 
     * @param success
     */
    public void setSuccess( Byte success )
    {
        this.success = success;
    }
    /**
     * Get the "success" field value
     * This field is mapped on the database column "success" ( type "tinyint" ) 
     * @return the field value
     */
    public Byte getSuccess()
    {
        return this.success;
    }

    //--- DATABASE MAPPING : success_state ( varchar ) 
    /**
     * Set the "successState" field value
     * This field is mapped on the database column "success_state" ( type "varchar" ) 
     * @param successState
     */
    public void setSuccessState( String successState )
    {
        this.successState = successState;
    }
    /**
     * Get the "successState" field value
     * This field is mapped on the database column "success_state" ( type "varchar" ) 
     * @return the field value
     */
    public String getSuccessState()
    {
        return this.successState;
    }

    //--- DATABASE MAPPING : create_date ( datetime ) 
    /**
     * Set the "createDate" field value
     * This field is mapped on the database column "create_date" ( type "datetime" ) 
     * @param createDate
     */
    public void setCreateDate( Date createDate )
    {
        this.createDate = createDate;
    }
    /**
     * Get the "createDate" field value
     * This field is mapped on the database column "create_date" ( type "datetime" ) 
     * @return the field value
     */
    public Date getCreateDate()
    {
        return this.createDate;
    }

    //--- DATABASE MAPPING : update_date ( datetime ) 
    /**
     * Set the "updateDate" field value
     * This field is mapped on the database column "update_date" ( type "datetime" ) 
     * @param updateDate
     */
    public void setUpdateDate( Date updateDate )
    {
        this.updateDate = updateDate;
    }
    /**
     * Get the "updateDate" field value
     * This field is mapped on the database column "update_date" ( type "datetime" ) 
     * @return the field value
     */
    public Date getUpdateDate()
    {
        return this.updateDate;
    }

    //--- DATABASE MAPPING : multi_borrower ( tinyint ) 
    /**
     * Set the "multiBorrower" field value
     * This field is mapped on the database column "multi_borrower" ( type "tinyint" ) 
     * @param multiBorrower
     */
    public void setMultiBorrower( Byte multiBorrower )
    {
        this.multiBorrower = multiBorrower;
    }
    /**
     * Get the "multiBorrower" field value
     * This field is mapped on the database column "multi_borrower" ( type "tinyint" ) 
     * @return the field value
     */
    public Byte getMultiBorrower()
    {
        return this.multiBorrower;
    }

    //--- DATABASE MAPPING : loan_genNumber ( varchar ) 
    /**
     * Set the "loanGennumber" field value
     * This field is mapped on the database column "loan_genNumber" ( type "varchar" ) 
     * @param loanGennumber
     */
    public void setLoanGennumber( String loanGennumber )
    {
        this.loanGennumber = loanGennumber;
    }
    /**
     * Get the "loanGennumber" field value
     * This field is mapped on the database column "loan_genNumber" ( type "varchar" ) 
     * @return the field value
     */
    public String getLoanGennumber()
    {
        return this.loanGennumber;
    }

    public void setTLoanHouse( TLoanHouse tLoanHouse )
    {
        this.tLoanHouse = tLoanHouse;
    }
    public TLoanHouse getTLoanHouse()
    {
        return this.tLoanHouse;
    }

    public void setListOfTSpousefriend( List<TSpousefriend> listOfTSpousefriend )
    {
        this.listOfTSpousefriend = listOfTSpousefriend;
    }
    public List<TSpousefriend> getListOfTSpousefriend()
    {
        return this.listOfTSpousefriend;
    }

    public void setListOfTLoanConsult( List<TLoanConsult> listOfTLoanConsult )
    {
        this.listOfTLoanConsult = listOfTLoanConsult;
    }
    public List<TLoanConsult> getListOfTLoanConsult()
    {
        return this.listOfTLoanConsult;
    }

    public void setTCustomer( TCustomer tCustomer )
    {
        this.tCustomer = tCustomer;
    }
    public TCustomer getTCustomer()
    {
        return this.tCustomer;
    }

    public void setTLoanVechicle( TLoanVechicle tLoanVechicle )
    {
        this.tLoanVechicle = tLoanVechicle;
    }
    public TLoanVechicle getTLoanVechicle()
    {
        return this.tLoanVechicle;
    }

    public void setTLoanBoss( TLoanBoss tLoanBoss )
    {
        this.tLoanBoss = tLoanBoss;
    }
    public TLoanBoss getTLoanBoss()
    {
        return this.tLoanBoss;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(loanId); 
        sb.append("|"); 
        sb.append(customerPid); 
        sb.append( "|" ); 
        sb.append(username); 
        sb.append( "|" ); 
        sb.append(loanLimit); 
        sb.append( "|" ); 
        sb.append(loanMonth); 
        sb.append( "|" ); 
        sb.append(loanReturntype); 
        sb.append( "|" ); 
        sb.append(loanUsage); 
        sb.append( "|" ); 
        sb.append(loanOpentime); 
        sb.append( "|" ); 
        sb.append(bankAccount); 
        sb.append( "|" ); 
        sb.append(bankAccountno); 
        sb.append( "|" ); 
        sb.append(bankOpenname); 
        sb.append( "|" ); 
        sb.append(bankType); 
        sb.append( "|" ); 
        sb.append(loanBigtype); 
        sb.append( "|" ); 
        sb.append(loanSmalltype); 
        sb.append( "|" ); 
        sb.append(state); 
        sb.append( "|" ); 
        sb.append(success); 
        sb.append( "|" ); 
        sb.append(successState); 
        sb.append( "|" ); 
        sb.append(createDate); 
        sb.append( "|" ); 
        sb.append(updateDate); 
        sb.append( "|" ); 
        sb.append(multiBorrower); 
        sb.append( "|" ); 
        sb.append(loanGennumber); 
        return sb.toString();
    }

}
