/*
 * Java bean class for entity table t_loan_boss 
 * Created on 17 ËÄÔÂ 2013 ( Time 20:42:50 )
 * Generated by Telosys Tools Generator ( version 2.0.3 )
 */

package com.hlj.tech.kdkj.customer.entities ;

import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;

/**
 * Entity bean for table "t_loan_boss"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TLoanBoss implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    loanBossId   ; // Primary Key

    private Integer    loanPid      ;
    private Byte       companyYears ;
    private BigDecimal companySquare ;
    private BigDecimal companyOpenmoney ;
    private TLoan      tLoan       ;
    /**
     * Default constructor
     */
    public TLoanBoss()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "loanBossId" field value
     * This field is mapped on the database column "loan_boss_id" ( type "int", ) 
     * @param loanBossId
     */
	public void setLoanBossId( Integer loanBossId )
    {
        this.loanBossId = loanBossId ;
    }
    /**
     * Get the "loanBossId" field value
     * This field is mapped on the database column "loan_boss_id" ( type "int", ) 
     * @return the field value
     */
	public Integer getLoanBossId()
    {
        return this.loanBossId;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : loan_pid ( int ) 
    /**
     * Set the "loanPid" field value
     * This field is mapped on the database column "loan_pid" ( type "int" ) 
     * @param loanPid
     */
    public void setLoanPid( Integer loanPid )
    {
        this.loanPid = loanPid;
    }
    /**
     * Get the "loanPid" field value
     * This field is mapped on the database column "loan_pid" ( type "int" ) 
     * @return the field value
     */
    public Integer getLoanPid()
    {
        return this.loanPid;
    }

    //--- DATABASE MAPPING : company_years ( tinyint ) 
    /**
     * Set the "companyYears" field value
     * This field is mapped on the database column "company_years" ( type "tinyint" ) 
     * @param companyYears
     */
    public void setCompanyYears( Byte companyYears )
    {
        this.companyYears = companyYears;
    }
    /**
     * Get the "companyYears" field value
     * This field is mapped on the database column "company_years" ( type "tinyint" ) 
     * @return the field value
     */
    public Byte getCompanyYears()
    {
        return this.companyYears;
    }

    //--- DATABASE MAPPING : company_square ( decimal ) 
    /**
     * Set the "companySquare" field value
     * This field is mapped on the database column "company_square" ( type "decimal" ) 
     * @param companySquare
     */
    public void setCompanySquare( BigDecimal companySquare )
    {
        this.companySquare = companySquare;
    }
    /**
     * Get the "companySquare" field value
     * This field is mapped on the database column "company_square" ( type "decimal" ) 
     * @return the field value
     */
    public BigDecimal getCompanySquare()
    {
        return this.companySquare;
    }

    //--- DATABASE MAPPING : company_openMoney ( decimal ) 
    /**
     * Set the "companyOpenmoney" field value
     * This field is mapped on the database column "company_openMoney" ( type "decimal" ) 
     * @param companyOpenmoney
     */
    public void setCompanyOpenmoney( BigDecimal companyOpenmoney )
    {
        this.companyOpenmoney = companyOpenmoney;
    }
    /**
     * Get the "companyOpenmoney" field value
     * This field is mapped on the database column "company_openMoney" ( type "decimal" ) 
     * @return the field value
     */
    public BigDecimal getCompanyOpenmoney()
    {
        return this.companyOpenmoney;
    }

    public void setTLoan( TLoan tLoan )
    {
        this.tLoan = tLoan;
    }
    public TLoan getTLoan()
    {
        return this.tLoan;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(loanBossId); 
        sb.append("|"); 
        sb.append(loanPid); 
        sb.append( "|" ); 
        sb.append(companyYears); 
        sb.append( "|" ); 
        sb.append(companySquare); 
        sb.append( "|" ); 
        sb.append(companyOpenmoney); 
        return sb.toString();
    }

}
