/*
 * Java bean class for entity table t_loan_vechicle 
 * Created on 17 ËÄÔÂ 2013 ( Time 20:42:50 )
 * Generated by Telosys Tools Generator ( version 2.0.3 )
 */

package com.hlj.tech.kdkj.customer.entities ;

import java.io.Serializable;
import java.util.List;


/**
 * Entity bean for table "t_loan_vechicle"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TLoanVechicle implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    loanVechicleId ; // Primary Key

    private Integer    loanPid      ;
    private String     vechicleNumber ;
    private Byte       vechicleYear ;
    private String     engineNumber ;
    private Short      vechicleMiles ;
    private String     vechicleModeltype ;
    private String     applyType    ;
    private TLoan      tLoan       ;
    /**
     * Default constructor
     */
    public TLoanVechicle()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "loanVechicleId" field value
     * This field is mapped on the database column "loan_vechicle_id" ( type "int", ) 
     * @param loanVechicleId
     */
	public void setLoanVechicleId( Integer loanVechicleId )
    {
        this.loanVechicleId = loanVechicleId ;
    }
    /**
     * Get the "loanVechicleId" field value
     * This field is mapped on the database column "loan_vechicle_id" ( type "int", ) 
     * @return the field value
     */
	public Integer getLoanVechicleId()
    {
        return this.loanVechicleId;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : loan_pid ( int ) 
    /**
     * Set the "loanPid" field value
     * This field is mapped on the database column "loan_pid" ( type "int" ) 
     * @param loanPid
     */
    public void setLoanPid( Integer loanPid )
    {
        this.loanPid = loanPid;
    }
    /**
     * Get the "loanPid" field value
     * This field is mapped on the database column "loan_pid" ( type "int" ) 
     * @return the field value
     */
    public Integer getLoanPid()
    {
        return this.loanPid;
    }

    //--- DATABASE MAPPING : vechicle_number ( varchar ) 
    /**
     * Set the "vechicleNumber" field value
     * This field is mapped on the database column "vechicle_number" ( type "varchar" ) 
     * @param vechicleNumber
     */
    public void setVechicleNumber( String vechicleNumber )
    {
        this.vechicleNumber = vechicleNumber;
    }
    /**
     * Get the "vechicleNumber" field value
     * This field is mapped on the database column "vechicle_number" ( type "varchar" ) 
     * @return the field value
     */
    public String getVechicleNumber()
    {
        return this.vechicleNumber;
    }

    //--- DATABASE MAPPING : vechicle_year ( tinyint ) 
    /**
     * Set the "vechicleYear" field value
     * This field is mapped on the database column "vechicle_year" ( type "tinyint" ) 
     * @param vechicleYear
     */
    public void setVechicleYear( Byte vechicleYear )
    {
        this.vechicleYear = vechicleYear;
    }
    /**
     * Get the "vechicleYear" field value
     * This field is mapped on the database column "vechicle_year" ( type "tinyint" ) 
     * @return the field value
     */
    public Byte getVechicleYear()
    {
        return this.vechicleYear;
    }

    //--- DATABASE MAPPING : engine_number ( varchar ) 
    /**
     * Set the "engineNumber" field value
     * This field is mapped on the database column "engine_number" ( type "varchar" ) 
     * @param engineNumber
     */
    public void setEngineNumber( String engineNumber )
    {
        this.engineNumber = engineNumber;
    }
    /**
     * Get the "engineNumber" field value
     * This field is mapped on the database column "engine_number" ( type "varchar" ) 
     * @return the field value
     */
    public String getEngineNumber()
    {
        return this.engineNumber;
    }

    //--- DATABASE MAPPING : vechicle_miles ( smallint ) 
    /**
     * Set the "vechicleMiles" field value
     * This field is mapped on the database column "vechicle_miles" ( type "smallint" ) 
     * @param vechicleMiles
     */
    public void setVechicleMiles( Short vechicleMiles )
    {
        this.vechicleMiles = vechicleMiles;
    }
    /**
     * Get the "vechicleMiles" field value
     * This field is mapped on the database column "vechicle_miles" ( type "smallint" ) 
     * @return the field value
     */
    public Short getVechicleMiles()
    {
        return this.vechicleMiles;
    }

    //--- DATABASE MAPPING : vechicle_modelType ( varchar ) 
    /**
     * Set the "vechicleModeltype" field value
     * This field is mapped on the database column "vechicle_modelType" ( type "varchar" ) 
     * @param vechicleModeltype
     */
    public void setVechicleModeltype( String vechicleModeltype )
    {
        this.vechicleModeltype = vechicleModeltype;
    }
    /**
     * Get the "vechicleModeltype" field value
     * This field is mapped on the database column "vechicle_modelType" ( type "varchar" ) 
     * @return the field value
     */
    public String getVechicleModeltype()
    {
        return this.vechicleModeltype;
    }

    //--- DATABASE MAPPING : apply_type ( varchar ) 
    /**
     * Set the "applyType" field value
     * This field is mapped on the database column "apply_type" ( type "varchar" ) 
     * @param applyType
     */
    public void setApplyType( String applyType )
    {
        this.applyType = applyType;
    }
    /**
     * Get the "applyType" field value
     * This field is mapped on the database column "apply_type" ( type "varchar" ) 
     * @return the field value
     */
    public String getApplyType()
    {
        return this.applyType;
    }

    public void setTLoan( TLoan tLoan )
    {
        this.tLoan = tLoan;
    }
    public TLoan getTLoan()
    {
        return this.tLoan;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(loanVechicleId); 
        sb.append("|"); 
        sb.append(loanPid); 
        sb.append( "|" ); 
        sb.append(vechicleNumber); 
        sb.append( "|" ); 
        sb.append(vechicleYear); 
        sb.append( "|" ); 
        sb.append(engineNumber); 
        sb.append( "|" ); 
        sb.append(vechicleMiles); 
        sb.append( "|" ); 
        sb.append(vechicleModeltype); 
        sb.append( "|" ); 
        sb.append(applyType); 
        return sb.toString();
    }

}
