/*
 * Java bean class for entity table t_loan_house 
 * Created on 17 ËÄÔÂ 2013 ( Time 20:42:50 )
 * Generated by Telosys Tools Generator ( version 2.0.3 )
 */

package com.hlj.tech.kdkj.customer.entities ;

import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;

/**
 * Entity bean for table "t_loan_house"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TLoanHouse implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    loanHouseId  ; // Primary Key

    private Integer    loanPid      ;
    private String     applyType    ;
    private String     houseCardno  ;
    private String     houseOwner   ;
    private String     houseOwnergender ;
    private String     houseOwnercardno ;
    private Byte       houseOwnerage ;
    private String     houseColloate ;
    private String     houseColloategender ;
    private String     houseColloatercardno ;
    private Byte       houseColloateage ;
    private String     houseAddress ;
    private BigDecimal houseSquare  ;
    private BigDecimal houseValue   ;
    private Byte       houseLended  ;
    private BigDecimal houseLendedmoney ;
    private TLoan      tLoan       ;
    /**
     * Default constructor
     */
    public TLoanHouse()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "loanHouseId" field value
     * This field is mapped on the database column "loan_house_id" ( type "int", ) 
     * @param loanHouseId
     */
	public void setLoanHouseId( Integer loanHouseId )
    {
        this.loanHouseId = loanHouseId ;
    }
    /**
     * Get the "loanHouseId" field value
     * This field is mapped on the database column "loan_house_id" ( type "int", ) 
     * @return the field value
     */
	public Integer getLoanHouseId()
    {
        return this.loanHouseId;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : loan_pid ( int ) 
    /**
     * Set the "loanPid" field value
     * This field is mapped on the database column "loan_pid" ( type "int" ) 
     * @param loanPid
     */
    public void setLoanPid( Integer loanPid )
    {
        this.loanPid = loanPid;
    }
    /**
     * Get the "loanPid" field value
     * This field is mapped on the database column "loan_pid" ( type "int" ) 
     * @return the field value
     */
    public Integer getLoanPid()
    {
        return this.loanPid;
    }

    //--- DATABASE MAPPING : apply_type ( varchar ) 
    /**
     * Set the "applyType" field value
     * This field is mapped on the database column "apply_type" ( type "varchar" ) 
     * @param applyType
     */
    public void setApplyType( String applyType )
    {
        this.applyType = applyType;
    }
    /**
     * Get the "applyType" field value
     * This field is mapped on the database column "apply_type" ( type "varchar" ) 
     * @return the field value
     */
    public String getApplyType()
    {
        return this.applyType;
    }

    //--- DATABASE MAPPING : house_cardNo ( varchar ) 
    /**
     * Set the "houseCardno" field value
     * This field is mapped on the database column "house_cardNo" ( type "varchar" ) 
     * @param houseCardno
     */
    public void setHouseCardno( String houseCardno )
    {
        this.houseCardno = houseCardno;
    }
    /**
     * Get the "houseCardno" field value
     * This field is mapped on the database column "house_cardNo" ( type "varchar" ) 
     * @return the field value
     */
    public String getHouseCardno()
    {
        return this.houseCardno;
    }

    //--- DATABASE MAPPING : house_owner ( varchar ) 
    /**
     * Set the "houseOwner" field value
     * This field is mapped on the database column "house_owner" ( type "varchar" ) 
     * @param houseOwner
     */
    public void setHouseOwner( String houseOwner )
    {
        this.houseOwner = houseOwner;
    }
    /**
     * Get the "houseOwner" field value
     * This field is mapped on the database column "house_owner" ( type "varchar" ) 
     * @return the field value
     */
    public String getHouseOwner()
    {
        return this.houseOwner;
    }

    //--- DATABASE MAPPING : house_ownerGender ( char ) 
    /**
     * Set the "houseOwnergender" field value
     * This field is mapped on the database column "house_ownerGender" ( type "char" ) 
     * @param houseOwnergender
     */
    public void setHouseOwnergender( String houseOwnergender )
    {
        this.houseOwnergender = houseOwnergender;
    }
    /**
     * Get the "houseOwnergender" field value
     * This field is mapped on the database column "house_ownerGender" ( type "char" ) 
     * @return the field value
     */
    public String getHouseOwnergender()
    {
        return this.houseOwnergender;
    }

    //--- DATABASE MAPPING : house_ownerCardNo ( varchar ) 
    /**
     * Set the "houseOwnercardno" field value
     * This field is mapped on the database column "house_ownerCardNo" ( type "varchar" ) 
     * @param houseOwnercardno
     */
    public void setHouseOwnercardno( String houseOwnercardno )
    {
        this.houseOwnercardno = houseOwnercardno;
    }
    /**
     * Get the "houseOwnercardno" field value
     * This field is mapped on the database column "house_ownerCardNo" ( type "varchar" ) 
     * @return the field value
     */
    public String getHouseOwnercardno()
    {
        return this.houseOwnercardno;
    }

    //--- DATABASE MAPPING : house_ownerAge ( tinyint ) 
    /**
     * Set the "houseOwnerage" field value
     * This field is mapped on the database column "house_ownerAge" ( type "tinyint" ) 
     * @param houseOwnerage
     */
    public void setHouseOwnerage( Byte houseOwnerage )
    {
        this.houseOwnerage = houseOwnerage;
    }
    /**
     * Get the "houseOwnerage" field value
     * This field is mapped on the database column "house_ownerAge" ( type "tinyint" ) 
     * @return the field value
     */
    public Byte getHouseOwnerage()
    {
        return this.houseOwnerage;
    }

    //--- DATABASE MAPPING : house_colloate ( varchar ) 
    /**
     * Set the "houseColloate" field value
     * This field is mapped on the database column "house_colloate" ( type "varchar" ) 
     * @param houseColloate
     */
    public void setHouseColloate( String houseColloate )
    {
        this.houseColloate = houseColloate;
    }
    /**
     * Get the "houseColloate" field value
     * This field is mapped on the database column "house_colloate" ( type "varchar" ) 
     * @return the field value
     */
    public String getHouseColloate()
    {
        return this.houseColloate;
    }

    //--- DATABASE MAPPING : house_colloateGender ( char ) 
    /**
     * Set the "houseColloategender" field value
     * This field is mapped on the database column "house_colloateGender" ( type "char" ) 
     * @param houseColloategender
     */
    public void setHouseColloategender( String houseColloategender )
    {
        this.houseColloategender = houseColloategender;
    }
    /**
     * Get the "houseColloategender" field value
     * This field is mapped on the database column "house_colloateGender" ( type "char" ) 
     * @return the field value
     */
    public String getHouseColloategender()
    {
        return this.houseColloategender;
    }

    //--- DATABASE MAPPING : house_colloaterCardNo ( varchar ) 
    /**
     * Set the "houseColloatercardno" field value
     * This field is mapped on the database column "house_colloaterCardNo" ( type "varchar" ) 
     * @param houseColloatercardno
     */
    public void setHouseColloatercardno( String houseColloatercardno )
    {
        this.houseColloatercardno = houseColloatercardno;
    }
    /**
     * Get the "houseColloatercardno" field value
     * This field is mapped on the database column "house_colloaterCardNo" ( type "varchar" ) 
     * @return the field value
     */
    public String getHouseColloatercardno()
    {
        return this.houseColloatercardno;
    }

    //--- DATABASE MAPPING : house_colloateAge ( tinyint ) 
    /**
     * Set the "houseColloateage" field value
     * This field is mapped on the database column "house_colloateAge" ( type "tinyint" ) 
     * @param houseColloateage
     */
    public void setHouseColloateage( Byte houseColloateage )
    {
        this.houseColloateage = houseColloateage;
    }
    /**
     * Get the "houseColloateage" field value
     * This field is mapped on the database column "house_colloateAge" ( type "tinyint" ) 
     * @return the field value
     */
    public Byte getHouseColloateage()
    {
        return this.houseColloateage;
    }

    //--- DATABASE MAPPING : house_address ( varchar ) 
    /**
     * Set the "houseAddress" field value
     * This field is mapped on the database column "house_address" ( type "varchar" ) 
     * @param houseAddress
     */
    public void setHouseAddress( String houseAddress )
    {
        this.houseAddress = houseAddress;
    }
    /**
     * Get the "houseAddress" field value
     * This field is mapped on the database column "house_address" ( type "varchar" ) 
     * @return the field value
     */
    public String getHouseAddress()
    {
        return this.houseAddress;
    }

    //--- DATABASE MAPPING : house_square ( decimal ) 
    /**
     * Set the "houseSquare" field value
     * This field is mapped on the database column "house_square" ( type "decimal" ) 
     * @param houseSquare
     */
    public void setHouseSquare( BigDecimal houseSquare )
    {
        this.houseSquare = houseSquare;
    }
    /**
     * Get the "houseSquare" field value
     * This field is mapped on the database column "house_square" ( type "decimal" ) 
     * @return the field value
     */
    public BigDecimal getHouseSquare()
    {
        return this.houseSquare;
    }

    //--- DATABASE MAPPING : house_value ( decimal ) 
    /**
     * Set the "houseValue" field value
     * This field is mapped on the database column "house_value" ( type "decimal" ) 
     * @param houseValue
     */
    public void setHouseValue( BigDecimal houseValue )
    {
        this.houseValue = houseValue;
    }
    /**
     * Get the "houseValue" field value
     * This field is mapped on the database column "house_value" ( type "decimal" ) 
     * @return the field value
     */
    public BigDecimal getHouseValue()
    {
        return this.houseValue;
    }

    //--- DATABASE MAPPING : house_lended ( tinyint ) 
    /**
     * Set the "houseLended" field value
     * This field is mapped on the database column "house_lended" ( type "tinyint" ) 
     * @param houseLended
     */
    public void setHouseLended( Byte houseLended )
    {
        this.houseLended = houseLended;
    }
    /**
     * Get the "houseLended" field value
     * This field is mapped on the database column "house_lended" ( type "tinyint" ) 
     * @return the field value
     */
    public Byte getHouseLended()
    {
        return this.houseLended;
    }

    //--- DATABASE MAPPING : house_lendedMoney ( decimal ) 
    /**
     * Set the "houseLendedmoney" field value
     * This field is mapped on the database column "house_lendedMoney" ( type "decimal" ) 
     * @param houseLendedmoney
     */
    public void setHouseLendedmoney( BigDecimal houseLendedmoney )
    {
        this.houseLendedmoney = houseLendedmoney;
    }
    /**
     * Get the "houseLendedmoney" field value
     * This field is mapped on the database column "house_lendedMoney" ( type "decimal" ) 
     * @return the field value
     */
    public BigDecimal getHouseLendedmoney()
    {
        return this.houseLendedmoney;
    }

    public void setTLoan( TLoan tLoan )
    {
        this.tLoan = tLoan;
    }
    public TLoan getTLoan()
    {
        return this.tLoan;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(loanHouseId); 
        sb.append("|"); 
        sb.append(loanPid); 
        sb.append( "|" ); 
        sb.append(applyType); 
        sb.append( "|" ); 
        sb.append(houseCardno); 
        sb.append( "|" ); 
        sb.append(houseOwner); 
        sb.append( "|" ); 
        sb.append(houseOwnergender); 
        sb.append( "|" ); 
        sb.append(houseOwnercardno); 
        sb.append( "|" ); 
        sb.append(houseOwnerage); 
        sb.append( "|" ); 
        sb.append(houseColloate); 
        sb.append( "|" ); 
        sb.append(houseColloategender); 
        sb.append( "|" ); 
        sb.append(houseColloatercardno); 
        sb.append( "|" ); 
        sb.append(houseColloateage); 
        sb.append( "|" ); 
        sb.append(houseAddress); 
        sb.append( "|" ); 
        sb.append(houseSquare); 
        sb.append( "|" ); 
        sb.append(houseValue); 
        sb.append( "|" ); 
        sb.append(houseLended); 
        sb.append( "|" ); 
        sb.append(houseLendedmoney); 
        return sb.toString();
    }

}
