/*
 * Java bean class for entity table t_loan_consult 
 * Created on 17 ËÄÔÂ 2013 ( Time 20:42:50 )
 * Generated by Telosys Tools Generator ( version 2.0.3 )
 */

package com.hlj.tech.kdkj.customer.entities ;

import java.io.Serializable;
import java.util.List;

import java.util.Date;

/**
 * Entity bean for table "t_loan_consult"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TLoanConsult implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    loanConsultid ; // Primary Key

    private Integer    loanPid      ;
    private String     comment      ;
    private String     consultUsername ;
    private Date       updateDate   ;
    private Date       createDate   ;
    private TLoan      tLoan       ;
    /**
     * Default constructor
     */
    public TLoanConsult()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "loanConsultid" field value
     * This field is mapped on the database column "loan_consultId" ( type "int", ) 
     * @param loanConsultid
     */
	public void setLoanConsultid( Integer loanConsultid )
    {
        this.loanConsultid = loanConsultid ;
    }
    /**
     * Get the "loanConsultid" field value
     * This field is mapped on the database column "loan_consultId" ( type "int", ) 
     * @return the field value
     */
	public Integer getLoanConsultid()
    {
        return this.loanConsultid;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : loan_pid ( int ) 
    /**
     * Set the "loanPid" field value
     * This field is mapped on the database column "loan_pid" ( type "int" ) 
     * @param loanPid
     */
    public void setLoanPid( Integer loanPid )
    {
        this.loanPid = loanPid;
    }
    /**
     * Get the "loanPid" field value
     * This field is mapped on the database column "loan_pid" ( type "int" ) 
     * @return the field value
     */
    public Integer getLoanPid()
    {
        return this.loanPid;
    }

    //--- DATABASE MAPPING : comment ( varchar ) 
    /**
     * Set the "comment" field value
     * This field is mapped on the database column "comment" ( type "varchar" ) 
     * @param comment
     */
    public void setComment( String comment )
    {
        this.comment = comment;
    }
    /**
     * Get the "comment" field value
     * This field is mapped on the database column "comment" ( type "varchar" ) 
     * @return the field value
     */
    public String getComment()
    {
        return this.comment;
    }

    //--- DATABASE MAPPING : consult_username ( varchar ) 
    /**
     * Set the "consultUsername" field value
     * This field is mapped on the database column "consult_username" ( type "varchar" ) 
     * @param consultUsername
     */
    public void setConsultUsername( String consultUsername )
    {
        this.consultUsername = consultUsername;
    }
    /**
     * Get the "consultUsername" field value
     * This field is mapped on the database column "consult_username" ( type "varchar" ) 
     * @return the field value
     */
    public String getConsultUsername()
    {
        return this.consultUsername;
    }

    //--- DATABASE MAPPING : update_date ( date ) 
    /**
     * Set the "updateDate" field value
     * This field is mapped on the database column "update_date" ( type "date" ) 
     * @param updateDate
     */
    public void setUpdateDate( Date updateDate )
    {
        this.updateDate = updateDate;
    }
    /**
     * Get the "updateDate" field value
     * This field is mapped on the database column "update_date" ( type "date" ) 
     * @return the field value
     */
    public Date getUpdateDate()
    {
        return this.updateDate;
    }

    //--- DATABASE MAPPING : create_date ( date ) 
    /**
     * Set the "createDate" field value
     * This field is mapped on the database column "create_date" ( type "date" ) 
     * @param createDate
     */
    public void setCreateDate( Date createDate )
    {
        this.createDate = createDate;
    }
    /**
     * Get the "createDate" field value
     * This field is mapped on the database column "create_date" ( type "date" ) 
     * @return the field value
     */
    public Date getCreateDate()
    {
        return this.createDate;
    }

    public void setTLoan( TLoan tLoan )
    {
        this.tLoan = tLoan;
    }
    public TLoan getTLoan()
    {
        return this.tLoan;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(loanConsultid); 
        sb.append("|"); 
        sb.append(loanPid); 
        sb.append( "|" ); 
        sb.append(comment); 
        sb.append( "|" ); 
        sb.append(consultUsername); 
        sb.append( "|" ); 
        sb.append(updateDate); 
        sb.append( "|" ); 
        sb.append(createDate); 
        return sb.toString();
    }

}
