/*
 * Java bean class for entity table t_spousefriend 
 * Created on 17 ËÄÔÂ 2013 ( Time 20:42:50 )
 * Generated by Telosys Tools Generator ( version 2.0.3 )
 */

package com.hlj.tech.kdkj.customer.entities ;

import java.io.Serializable;
import java.util.List;

import java.util.Date;

/**
 * Entity bean for table "t_spousefriend"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TSpousefriend implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    spouseFriendid ; // Primary Key

    private Integer    customerPid  ;
    private Integer    loanPid      ;
    private String     name         ;
    private String     gender       ;
    private String     cardno       ;
    private String     cardType     ;
    private Short      age          ;
    private String     address      ;
    private String     telephone    ;
    private String     homePhone    ;
    private String     officeCompany ;
    private String     officeTelephone ;
    private String     departTypename ;
    private String     officeAddress ;
    private Integer    yearSalary   ;
    private Integer    officeYear   ;
    private Date       birthday     ;
    private String     relationType ;
    private String     relationTypename ;
    private TCustomer  tCustomer   ;
    private TLoan      tLoan       ;
    /**
     * Default constructor
     */
    public TSpousefriend()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "spouseFriendid" field value
     * This field is mapped on the database column "spouse_friendId" ( type "int", ) 
     * @param spouseFriendid
     */
	public void setSpouseFriendid( Integer spouseFriendid )
    {
        this.spouseFriendid = spouseFriendid ;
    }
    /**
     * Get the "spouseFriendid" field value
     * This field is mapped on the database column "spouse_friendId" ( type "int", ) 
     * @return the field value
     */
	public Integer getSpouseFriendid()
    {
        return this.spouseFriendid;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : customer_pid ( int ) 
    /**
     * Set the "customerPid" field value
     * This field is mapped on the database column "customer_pid" ( type "int" ) 
     * @param customerPid
     */
    public void setCustomerPid( Integer customerPid )
    {
        this.customerPid = customerPid;
    }
    /**
     * Get the "customerPid" field value
     * This field is mapped on the database column "customer_pid" ( type "int" ) 
     * @return the field value
     */
    public Integer getCustomerPid()
    {
        return this.customerPid;
    }

    //--- DATABASE MAPPING : loan_pid ( int ) 
    /**
     * Set the "loanPid" field value
     * This field is mapped on the database column "loan_pid" ( type "int" ) 
     * @param loanPid
     */
    public void setLoanPid( Integer loanPid )
    {
        this.loanPid = loanPid;
    }
    /**
     * Get the "loanPid" field value
     * This field is mapped on the database column "loan_pid" ( type "int" ) 
     * @return the field value
     */
    public Integer getLoanPid()
    {
        return this.loanPid;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    /**
     * Set the "name" field value
     * This field is mapped on the database column "name" ( type "varchar" ) 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    }
    /**
     * Get the "name" field value
     * This field is mapped on the database column "name" ( type "varchar" ) 
     * @return the field value
     */
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : gender ( varchar ) 
    /**
     * Set the "gender" field value
     * This field is mapped on the database column "gender" ( type "varchar" ) 
     * @param gender
     */
    public void setGender( String gender )
    {
        this.gender = gender;
    }
    /**
     * Get the "gender" field value
     * This field is mapped on the database column "gender" ( type "varchar" ) 
     * @return the field value
     */
    public String getGender()
    {
        return this.gender;
    }

    //--- DATABASE MAPPING : cardNo ( varchar ) 
    /**
     * Set the "cardno" field value
     * This field is mapped on the database column "cardNo" ( type "varchar" ) 
     * @param cardno
     */
    public void setCardno( String cardno )
    {
        this.cardno = cardno;
    }
    /**
     * Get the "cardno" field value
     * This field is mapped on the database column "cardNo" ( type "varchar" ) 
     * @return the field value
     */
    public String getCardno()
    {
        return this.cardno;
    }

    //--- DATABASE MAPPING : card_type ( varchar ) 
    /**
     * Set the "cardType" field value
     * This field is mapped on the database column "card_type" ( type "varchar" ) 
     * @param cardType
     */
    public void setCardType( String cardType )
    {
        this.cardType = cardType;
    }
    /**
     * Get the "cardType" field value
     * This field is mapped on the database column "card_type" ( type "varchar" ) 
     * @return the field value
     */
    public String getCardType()
    {
        return this.cardType;
    }

    //--- DATABASE MAPPING : age ( smallint ) 
    /**
     * Set the "age" field value
     * This field is mapped on the database column "age" ( type "smallint" ) 
     * @param age
     */
    public void setAge( Short age )
    {
        this.age = age;
    }
    /**
     * Get the "age" field value
     * This field is mapped on the database column "age" ( type "smallint" ) 
     * @return the field value
     */
    public Short getAge()
    {
        return this.age;
    }

    //--- DATABASE MAPPING : address ( varchar ) 
    /**
     * Set the "address" field value
     * This field is mapped on the database column "address" ( type "varchar" ) 
     * @param address
     */
    public void setAddress( String address )
    {
        this.address = address;
    }
    /**
     * Get the "address" field value
     * This field is mapped on the database column "address" ( type "varchar" ) 
     * @return the field value
     */
    public String getAddress()
    {
        return this.address;
    }

    //--- DATABASE MAPPING : telephone ( varchar ) 
    /**
     * Set the "telephone" field value
     * This field is mapped on the database column "telephone" ( type "varchar" ) 
     * @param telephone
     */
    public void setTelephone( String telephone )
    {
        this.telephone = telephone;
    }
    /**
     * Get the "telephone" field value
     * This field is mapped on the database column "telephone" ( type "varchar" ) 
     * @return the field value
     */
    public String getTelephone()
    {
        return this.telephone;
    }

    //--- DATABASE MAPPING : home_phone ( varchar ) 
    /**
     * Set the "homePhone" field value
     * This field is mapped on the database column "home_phone" ( type "varchar" ) 
     * @param homePhone
     */
    public void setHomePhone( String homePhone )
    {
        this.homePhone = homePhone;
    }
    /**
     * Get the "homePhone" field value
     * This field is mapped on the database column "home_phone" ( type "varchar" ) 
     * @return the field value
     */
    public String getHomePhone()
    {
        return this.homePhone;
    }

    //--- DATABASE MAPPING : office_company ( varchar ) 
    /**
     * Set the "officeCompany" field value
     * This field is mapped on the database column "office_company" ( type "varchar" ) 
     * @param officeCompany
     */
    public void setOfficeCompany( String officeCompany )
    {
        this.officeCompany = officeCompany;
    }
    /**
     * Get the "officeCompany" field value
     * This field is mapped on the database column "office_company" ( type "varchar" ) 
     * @return the field value
     */
    public String getOfficeCompany()
    {
        return this.officeCompany;
    }

    //--- DATABASE MAPPING : office_telephone ( varchar ) 
    /**
     * Set the "officeTelephone" field value
     * This field is mapped on the database column "office_telephone" ( type "varchar" ) 
     * @param officeTelephone
     */
    public void setOfficeTelephone( String officeTelephone )
    {
        this.officeTelephone = officeTelephone;
    }
    /**
     * Get the "officeTelephone" field value
     * This field is mapped on the database column "office_telephone" ( type "varchar" ) 
     * @return the field value
     */
    public String getOfficeTelephone()
    {
        return this.officeTelephone;
    }

    //--- DATABASE MAPPING : depart_typename ( varchar ) 
    /**
     * Set the "departTypename" field value
     * This field is mapped on the database column "depart_typename" ( type "varchar" ) 
     * @param departTypename
     */
    public void setDepartTypename( String departTypename )
    {
        this.departTypename = departTypename;
    }
    /**
     * Get the "departTypename" field value
     * This field is mapped on the database column "depart_typename" ( type "varchar" ) 
     * @return the field value
     */
    public String getDepartTypename()
    {
        return this.departTypename;
    }

    //--- DATABASE MAPPING : office_address ( varchar ) 
    /**
     * Set the "officeAddress" field value
     * This field is mapped on the database column "office_address" ( type "varchar" ) 
     * @param officeAddress
     */
    public void setOfficeAddress( String officeAddress )
    {
        this.officeAddress = officeAddress;
    }
    /**
     * Get the "officeAddress" field value
     * This field is mapped on the database column "office_address" ( type "varchar" ) 
     * @return the field value
     */
    public String getOfficeAddress()
    {
        return this.officeAddress;
    }

    //--- DATABASE MAPPING : year_salary ( int ) 
    /**
     * Set the "yearSalary" field value
     * This field is mapped on the database column "year_salary" ( type "int" ) 
     * @param yearSalary
     */
    public void setYearSalary( Integer yearSalary )
    {
        this.yearSalary = yearSalary;
    }
    /**
     * Get the "yearSalary" field value
     * This field is mapped on the database column "year_salary" ( type "int" ) 
     * @return the field value
     */
    public Integer getYearSalary()
    {
        return this.yearSalary;
    }

    //--- DATABASE MAPPING : office_year ( int ) 
    /**
     * Set the "officeYear" field value
     * This field is mapped on the database column "office_year" ( type "int" ) 
     * @param officeYear
     */
    public void setOfficeYear( Integer officeYear )
    {
        this.officeYear = officeYear;
    }
    /**
     * Get the "officeYear" field value
     * This field is mapped on the database column "office_year" ( type "int" ) 
     * @return the field value
     */
    public Integer getOfficeYear()
    {
        return this.officeYear;
    }

    //--- DATABASE MAPPING : birthday ( date ) 
    /**
     * Set the "birthday" field value
     * This field is mapped on the database column "birthday" ( type "date" ) 
     * @param birthday
     */
    public void setBirthday( Date birthday )
    {
        this.birthday = birthday;
    }
    /**
     * Get the "birthday" field value
     * This field is mapped on the database column "birthday" ( type "date" ) 
     * @return the field value
     */
    public Date getBirthday()
    {
        return this.birthday;
    }

    //--- DATABASE MAPPING : relation_type ( varchar ) 
    /**
     * Set the "relationType" field value
     * This field is mapped on the database column "relation_type" ( type "varchar" ) 
     * @param relationType
     */
    public void setRelationType( String relationType )
    {
        this.relationType = relationType;
    }
    /**
     * Get the "relationType" field value
     * This field is mapped on the database column "relation_type" ( type "varchar" ) 
     * @return the field value
     */
    public String getRelationType()
    {
        return this.relationType;
    }

    //--- DATABASE MAPPING : relation_typeName ( varchar ) 
    /**
     * Set the "relationTypename" field value
     * This field is mapped on the database column "relation_typeName" ( type "varchar" ) 
     * @param relationTypename
     */
    public void setRelationTypename( String relationTypename )
    {
        this.relationTypename = relationTypename;
    }
    /**
     * Get the "relationTypename" field value
     * This field is mapped on the database column "relation_typeName" ( type "varchar" ) 
     * @return the field value
     */
    public String getRelationTypename()
    {
        return this.relationTypename;
    }

    public void setTCustomer( TCustomer tCustomer )
    {
        this.tCustomer = tCustomer;
    }
    public TCustomer getTCustomer()
    {
        return this.tCustomer;
    }

    public void setTLoan( TLoan tLoan )
    {
        this.tLoan = tLoan;
    }
    public TLoan getTLoan()
    {
        return this.tLoan;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(spouseFriendid); 
        sb.append("|"); 
        sb.append(customerPid); 
        sb.append( "|" ); 
        sb.append(loanPid); 
        sb.append( "|" ); 
        sb.append(name); 
        sb.append( "|" ); 
        sb.append(gender); 
        sb.append( "|" ); 
        sb.append(cardno); 
        sb.append( "|" ); 
        sb.append(cardType); 
        sb.append( "|" ); 
        sb.append(age); 
        sb.append( "|" ); 
        sb.append(address); 
        sb.append( "|" ); 
        sb.append(telephone); 
        sb.append( "|" ); 
        sb.append(homePhone); 
        sb.append( "|" ); 
        sb.append(officeCompany); 
        sb.append( "|" ); 
        sb.append(officeTelephone); 
        sb.append( "|" ); 
        sb.append(departTypename); 
        sb.append( "|" ); 
        sb.append(officeAddress); 
        sb.append( "|" ); 
        sb.append(yearSalary); 
        sb.append( "|" ); 
        sb.append(officeYear); 
        sb.append( "|" ); 
        sb.append(birthday); 
        sb.append( "|" ); 
        sb.append(relationType); 
        sb.append( "|" ); 
        sb.append(relationTypename); 
        return sb.toString();
    }

}
