/*
 * Java bean class for entity table v_loan_consult 
 * Created on 19 ËÄÔÂ 2013 ( Time 10:51:54 )
 * Generated by Telosys Tools Generator ( version 2.0.3 )
 */

package com.hlj.tech.kdkj.customer.entities ;

import java.io.Serializable;
import java.util.List;


/**
 * Entity bean for table "v_loan_consult"
 * 
 * @author Telosys Tools Generator
 *
 */
public class VLoanConsult implements Serializable
{
    private static final long serialVersionUID = 1L;


    private int        loanId       ;
    private String     username     ;
    private String     city         ;
    private String     name         ;
    /**
     * Default constructor
     */
    public VLoanConsult()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : loan_id ( int ) 
    /**
     * Set the "loanId" field value
     * This field is mapped on the database column "loan_id" ( type "int" ) 
     * @param loanId
     */
    public void setLoanId( int loanId )
    {
        this.loanId = loanId;
    }
    /**
     * Get the "loanId" field value
     * This field is mapped on the database column "loan_id" ( type "int" ) 
     * @return the field value
     */
    public int getLoanId()
    {
        return this.loanId;
    }

    //--- DATABASE MAPPING : userName ( varchar ) 
    /**
     * Set the "username" field value
     * This field is mapped on the database column "userName" ( type "varchar" ) 
     * @param username
     */
    public void setUsername( String username )
    {
        this.username = username;
    }
    /**
     * Get the "username" field value
     * This field is mapped on the database column "userName" ( type "varchar" ) 
     * @return the field value
     */
    public String getUsername()
    {
        return this.username;
    }

    //--- DATABASE MAPPING : city ( varchar ) 
    /**
     * Set the "city" field value
     * This field is mapped on the database column "city" ( type "varchar" ) 
     * @param city
     */
    public void setCity( String city )
    {
        this.city = city;
    }
    /**
     * Get the "city" field value
     * This field is mapped on the database column "city" ( type "varchar" ) 
     * @return the field value
     */
    public String getCity()
    {
        return this.city;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    /**
     * Set the "name" field value
     * This field is mapped on the database column "name" ( type "varchar" ) 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    }
    /**
     * Get the "name" field value
     * This field is mapped on the database column "name" ( type "varchar" ) 
     * @return the field value
     */
    public String getName()
    {
        return this.name;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(loanId); 
        sb.append( "|" ); 
        sb.append(username); 
        sb.append( "|" ); 
        sb.append(city); 
        sb.append( "|" ); 
        sb.append(name); 
        return sb.toString();
    }

}
