//-----------------------------------------------------------
// This is a generated class. Avoid customizing code here !
// Generated by Telosys Tools Generator - version : 2.0.3
// Date : 12 ËÄÔÂ 2013 - Time 23:24:03
//-----------------------------------------------------------
// This class was generated by the standard template
// Template name    : vo_bean.vm
// Template author  : Stephane LABBE 
// Template version : 1.0.0 ( Aout 17 - 2011 ) 
//-----------------------------------------------------------

package com.hlj.tech.kdkj.auto.entities;

import java.io.Serializable;



import javax.persistence.*;


@Entity
@Table(name="t_city", catalog="bdf" )
public class TCity implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="id", nullable=false)
    private short      id            ;
    
    @Column(name="province_id")
    private Short      provinceId    ;
    
    @Column(name="name", length=20)
    private String     name          ;
    

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="province_id", referencedColumnName="id", insertable=false, updatable=false)
    private TProvince  tProvince   ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TCity()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR ENTITY FIELDS
    //----------------------------------------------------------------------
    //--- DB PRIMARY KEY : id ( smallint ) 
    public void setId( short value )
    {
        this.id = value;
    }
    public short getId()
    {
        return this.id;
    }

    //--- DB COLUMN : province_id ( smallint ) 
    public void setProvinceId( Short value )
    {
        this.provinceId = value;
    }
    public Short getProvinceId()
    {
        return this.provinceId;
    }

    //--- DB COLUMN : name ( varchar ) 
    public void setName( String value )
    {
        this.name = value;
    }
    public String getName()
    {
        return this.name;
    }


    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTProvince( TProvince value )
    {
        this.tProvince = value;
    }
    public TProvince getTProvince()
    {
        return this.tProvince;
    }



}