//-----------------------------------------------------------
// This is a generated class. Avoid customizing code here !
// Generated by Telosys Tools Generator - version : 2.0.3
// Date : 17 ËÄÔÂ 2013 - Time 18:59:39
//-----------------------------------------------------------
// This class was generated by the standard template
// Template name    : vo_bean.vm
// Template author  : Stephane LABBE 
// Template version : 1.0.0 ( Aout 17 - 2011 ) 
//-----------------------------------------------------------

package com.hlj.tech.kdkj.customer.entities;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;


import java.util.List;
import javax.persistence.*;


@Entity
@Table(name="t_customer", catalog="bdf" )
public class TCustomer implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="customer_id", nullable=false)
    private Integer    customerId    ;
    
    @Column(name="name", length=50)
    private String     name          ;
    
    @Column(name="gender", length=4)
    private String     gender        ;
    
    @Column(name="card_type", length=10)
    private String     cardType      ;
    
    @Column(name="cardNo", length=20)
    private String     cardno        ;
    
    @Column(name="age")
    private Short      age           ;
    
    @Column(name="birth_address", length=50)
    private String     birthAddress  ;
    
    @Column(name="current_address", length=100)
    private String     currentAddress  ;
    
    @Column(name="telephone", nullable=false, length=15)
    private String     telephone     ;
    
    @Column(name="home_phone", length=15)
    private String     homePhone     ;
    
    @Column(name="parent_phone", length=15)
    private String     parentPhone   ;
    
    @Column(name="office_company", length=100)
    private String     officeCompany  ;
    
    @Column(name="office_address", length=100)
    private String     officeAddress  ;
    
    @Column(name="office_telephone", length=20)
    private String     officeTelephone  ;
    
    @Column(name="office_type", length=30)
    private String     officeType    ;
    
    @Column(name="office_persons")
    private Short      officePersons  ;
    
    @Column(name="office_totalMoney")
    private BigDecimal officeTotalmoney  ;
    
    @Column(name="office_myown")
    private Short      officeMyown   ;
    
    @Column(name="office_years")
    private BigDecimal officeYears   ;
    
    @Column(name="office_totalYears")
    private BigDecimal officeTotalyears  ;
    
    @Column(name="house_type", length=20)
    private String     houseType     ;
    
    @Column(name="house_monthReturn")
    private Short      houseMonthreturn  ;
    
    @Column(name="house_rent")
    private Short      houseRent     ;
    
    @Column(name="house_comment", length=100)
    private String     houseComment  ;
    
    @Column(name="married", length=10)
    private String     married       ;
    
    @Column(name="has_children")
    private Short      hasChildren   ;
    
    @Column(name="body_condition")
    private Short      bodyCondition  ;
    
    @Column(name="education_condition", length=20)
    private String     educationCondition  ;
    
    @Column(name="year_salary")
    private Integer    yearSalary    ;
    
    @Column(name="salary_comment", length=200)
    private String     salaryComment  ;
    
    @Column(name="province", length=15)
    private String     province      ;
    
    @Column(name="city", length=15)
    private String     city          ;
    
    @Temporal(TemporalType.DATE)
    @Column(name="birthday")
    private Date       birthday      ;
    
    @Column(name="email", length=40)
    private String     email         ;
    
    @Column(name="qq", length=20)
    private String     qq            ;
    
    @Temporal(TemporalType.DATE)
    @Column(name="create_date")
    private Date       createDate    ;
    
    @Temporal(TemporalType.DATE)
    @Column(name="update_date")
    private Date       updateDate    ;
    

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="tCustomer", targetEntity=TLoan.class)
    private List<TLoan> listOfTLoan ;
    
    @OneToMany(mappedBy="tCustomer", targetEntity=TSpousefriend.class)
    private List<TSpousefriend> listOfTSpousefriend;
    

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TCustomer()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR ENTITY FIELDS
    //----------------------------------------------------------------------
    //--- DB PRIMARY KEY : customer_id ( int ) 
    public void setCustomerId( Integer value )
    {
        this.customerId = value;
    }
    public Integer getCustomerId()
    {
        return this.customerId;
    }

    //--- DB COLUMN : name ( varchar ) 
    public void setName( String value )
    {
        this.name = value;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DB COLUMN : gender ( char ) 
    public void setGender( String value )
    {
        this.gender = value;
    }
    public String getGender()
    {
        return this.gender;
    }

    //--- DB COLUMN : card_type ( varchar ) 
    public void setCardType( String value )
    {
        this.cardType = value;
    }
    public String getCardType()
    {
        return this.cardType;
    }

    //--- DB COLUMN : cardNo ( varchar ) 
    public void setCardno( String value )
    {
        this.cardno = value;
    }
    public String getCardno()
    {
        return this.cardno;
    }

    //--- DB COLUMN : age ( smallint ) 
    public void setAge( Short value )
    {
        this.age = value;
    }
    public Short getAge()
    {
        return this.age;
    }

    //--- DB COLUMN : birth_address ( varchar ) 
    public void setBirthAddress( String value )
    {
        this.birthAddress = value;
    }
    public String getBirthAddress()
    {
        return this.birthAddress;
    }

    //--- DB COLUMN : current_address ( varchar ) 
    public void setCurrentAddress( String value )
    {
        this.currentAddress = value;
    }
    public String getCurrentAddress()
    {
        return this.currentAddress;
    }

    //--- DB COLUMN : telephone ( varchar ) 
    public void setTelephone( String value )
    {
        this.telephone = value;
    }
    public String getTelephone()
    {
        return this.telephone;
    }

    //--- DB COLUMN : home_phone ( varchar ) 
    public void setHomePhone( String value )
    {
        this.homePhone = value;
    }
    public String getHomePhone()
    {
        return this.homePhone;
    }

    //--- DB COLUMN : parent_phone ( varchar ) 
    public void setParentPhone( String value )
    {
        this.parentPhone = value;
    }
    public String getParentPhone()
    {
        return this.parentPhone;
    }

    //--- DB COLUMN : office_company ( varchar ) 
    public void setOfficeCompany( String value )
    {
        this.officeCompany = value;
    }
    public String getOfficeCompany()
    {
        return this.officeCompany;
    }

    //--- DB COLUMN : office_address ( varchar ) 
    public void setOfficeAddress( String value )
    {
        this.officeAddress = value;
    }
    public String getOfficeAddress()
    {
        return this.officeAddress;
    }

    //--- DB COLUMN : office_telephone ( varchar ) 
    public void setOfficeTelephone( String value )
    {
        this.officeTelephone = value;
    }
    public String getOfficeTelephone()
    {
        return this.officeTelephone;
    }

    //--- DB COLUMN : office_type ( varchar ) 
    public void setOfficeType( String value )
    {
        this.officeType = value;
    }
    public String getOfficeType()
    {
        return this.officeType;
    }

    //--- DB COLUMN : office_persons ( smallint ) 
    public void setOfficePersons( Short value )
    {
        this.officePersons = value;
    }
    public Short getOfficePersons()
    {
        return this.officePersons;
    }

    //--- DB COLUMN : office_totalMoney ( decimal ) 
    public void setOfficeTotalmoney( BigDecimal value )
    {
        this.officeTotalmoney = value;
    }
    public BigDecimal getOfficeTotalmoney()
    {
        return this.officeTotalmoney;
    }

    //--- DB COLUMN : office_myown ( smallint ) 
    public void setOfficeMyown( Short value )
    {
        this.officeMyown = value;
    }
    public Short getOfficeMyown()
    {
        return this.officeMyown;
    }

    //--- DB COLUMN : office_years ( decimal ) 
    public void setOfficeYears( BigDecimal value )
    {
        this.officeYears = value;
    }
    public BigDecimal getOfficeYears()
    {
        return this.officeYears;
    }

    //--- DB COLUMN : office_totalYears ( decimal ) 
    public void setOfficeTotalyears( BigDecimal value )
    {
        this.officeTotalyears = value;
    }
    public BigDecimal getOfficeTotalyears()
    {
        return this.officeTotalyears;
    }

    //--- DB COLUMN : house_type ( varchar ) 
    public void setHouseType( String value )
    {
        this.houseType = value;
    }
    public String getHouseType()
    {
        return this.houseType;
    }

    //--- DB COLUMN : house_monthReturn ( smallint ) 
    public void setHouseMonthreturn( Short value )
    {
        this.houseMonthreturn = value;
    }
    public Short getHouseMonthreturn()
    {
        return this.houseMonthreturn;
    }

    //--- DB COLUMN : house_rent ( smallint ) 
    public void setHouseRent( Short value )
    {
        this.houseRent = value;
    }
    public Short getHouseRent()
    {
        return this.houseRent;
    }

    //--- DB COLUMN : house_comment ( varchar ) 
    public void setHouseComment( String value )
    {
        this.houseComment = value;
    }
    public String getHouseComment()
    {
        return this.houseComment;
    }

    //--- DB COLUMN : married ( varchar ) 
    public void setMarried( String value )
    {
        this.married = value;
    }
    public String getMarried()
    {
        return this.married;
    }

    //--- DB COLUMN : has_children ( smallint ) 
    public void setHasChildren( Short value )
    {
        this.hasChildren = value;
    }
    public Short getHasChildren()
    {
        return this.hasChildren;
    }

    //--- DB COLUMN : body_condition ( smallint ) 
    public void setBodyCondition( Short value )
    {
        this.bodyCondition = value;
    }
    public Short getBodyCondition()
    {
        return this.bodyCondition;
    }

    //--- DB COLUMN : education_condition ( varchar ) 
    public void setEducationCondition( String value )
    {
        this.educationCondition = value;
    }
    public String getEducationCondition()
    {
        return this.educationCondition;
    }

    //--- DB COLUMN : year_salary ( int ) 
    public void setYearSalary( Integer value )
    {
        this.yearSalary = value;
    }
    public Integer getYearSalary()
    {
        return this.yearSalary;
    }

    //--- DB COLUMN : salary_comment ( varchar ) 
    public void setSalaryComment( String value )
    {
        this.salaryComment = value;
    }
    public String getSalaryComment()
    {
        return this.salaryComment;
    }

    //--- DB COLUMN : province ( varchar ) 
    public void setProvince( String value )
    {
        this.province = value;
    }
    public String getProvince()
    {
        return this.province;
    }

    //--- DB COLUMN : city ( varchar ) 
    public void setCity( String value )
    {
        this.city = value;
    }
    public String getCity()
    {
        return this.city;
    }

    //--- DB COLUMN : birthday ( date ) 
    public void setBirthday( Date value )
    {
        this.birthday = value;
    }
    public Date getBirthday()
    {
        return this.birthday;
    }

    //--- DB COLUMN : email ( varchar ) 
    public void setEmail( String value )
    {
        this.email = value;
    }
    public String getEmail()
    {
        return this.email;
    }

    //--- DB COLUMN : qq ( varchar ) 
    public void setQq( String value )
    {
        this.qq = value;
    }
    public String getQq()
    {
        return this.qq;
    }

    //--- DB COLUMN : create_date ( date ) 
    public void setCreateDate( Date value )
    {
        this.createDate = value;
    }
    public Date getCreateDate()
    {
        return this.createDate;
    }

    //--- DB COLUMN : update_date ( date ) 
    public void setUpdateDate( Date value )
    {
        this.updateDate = value;
    }
    public Date getUpdateDate()
    {
        return this.updateDate;
    }


    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfTLoan( List<TLoan> value )
    {
        this.listOfTLoan = value;
    }
    public List<TLoan> getListOfTLoan()
    {
        return this.listOfTLoan;
    }

    public void setListOfTSpousefriend( List<TSpousefriend> value )
    {
        this.listOfTSpousefriend = value;
    }
    public List<TSpousefriend> getListOfTSpousefriend()
    {
        return this.listOfTSpousefriend;
    }



}
 



///////////////////

name **
gender **
cardType **
cardno **
age **
birthAddress **
birthAddress         ooooooooooooooooooo
currentAddress **
telephone **
homePhone **
parentPhone **
officeCompany **
officeAddress **
officeTelephone **
officeType **
officePersons **
officeTotalmoney **
officeMyown **
officeYears **
officeTotalyears **
houseType **
houseMonthreturn **
houseRent **
houseComment **
married **
hasChildren **
bodyCondition **
educationCondition **
yearSalary **
salaryComment **
province **
city **
birthday **
email **
qq **
createDate **
updateDate **
