//-----------------------------------------------------------
// This is a generated class. Avoid customizing code here !
// Generated by Telosys Tools Generator - version : 2.0.3
// Date : 17 ËÄÔÂ 2013 - Time 20:42:50
//-----------------------------------------------------------
// This class was generated by the standard template
// Template name    : vo_bean.vm
// Template author  : Stephane LABBE 
// Template version : 1.0.0 ( Aout 17 - 2011 ) 
//-----------------------------------------------------------

package com.hlj.tech.kdkj.customer.entities;

import java.io.Serializable;

import java.math.BigDecimal;


import javax.persistence.*;


@Entity
@Table(name="t_loan_house", catalog="bdf" )
public class TLoanHouse implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="loan_house_id", nullable=false)
    private Integer    loanHouseId   ;
    
    @Column(name="loan_pid")
    private Integer    loanPid       ;
    
    @Column(name="apply_type", length=15)
    private String     applyType     ;
    
    @Column(name="house_cardNo", length=30)
    private String     houseCardno   ;
    
    @Column(name="house_owner", length=20)
    private String     houseOwner    ;
    
    @Column(name="house_ownerGender", length=4)
    private String     houseOwnergender  ;
    
    @Column(name="house_ownerCardNo", length=20)
    private String     houseOwnercardno  ;
    
    @Column(name="house_ownerAge")
    private Byte       houseOwnerage  ;
    
    @Column(name="house_colloate", length=20)
    private String     houseColloate  ;
    
    @Column(name="house_colloateGender", length=4)
    private String     houseColloategender  ;
    
    @Column(name="house_colloaterCardNo", length=20)
    private String     houseColloatercardno  ;
    
    @Column(name="house_colloateAge")
    private Byte       houseColloateage  ;
    
    @Column(name="house_address", length=50)
    private String     houseAddress  ;
    
    @Column(name="house_square")
    private BigDecimal houseSquare   ;
    
    @Column(name="house_value")
    private BigDecimal houseValue    ;
    
    @Column(name="house_lended")
    private Byte       houseLended   ;
    
    @Column(name="house_lendedMoney")
    private BigDecimal houseLendedmoney  ;
    

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToOne
    @JoinColumn(name="loan_pid", referencedColumnName="loan_id")
    private TLoan      tLoan       ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TLoanHouse()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR ENTITY FIELDS
    //----------------------------------------------------------------------
    //--- DB PRIMARY KEY : loan_house_id ( int ) 
    public void setLoanHouseId( Integer value )
    {
        this.loanHouseId = value;
    }
    public Integer getLoanHouseId()
    {
        return this.loanHouseId;
    }

    //--- DB COLUMN : loan_pid ( int ) 
    public void setLoanPid( Integer value )
    {
        this.loanPid = value;
    }
    public Integer getLoanPid()
    {
        return this.loanPid;
    }

    //--- DB COLUMN : apply_type ( varchar ) 
    public void setApplyType( String value )
    {
        this.applyType = value;
    }
    public String getApplyType()
    {
        return this.applyType;
    }

    //--- DB COLUMN : house_cardNo ( varchar ) 
    public void setHouseCardno( String value )
    {
        this.houseCardno = value;
    }
    public String getHouseCardno()
    {
        return this.houseCardno;
    }

    //--- DB COLUMN : house_owner ( varchar ) 
    public void setHouseOwner( String value )
    {
        this.houseOwner = value;
    }
    public String getHouseOwner()
    {
        return this.houseOwner;
    }

    //--- DB COLUMN : house_ownerGender ( char ) 
    public void setHouseOwnergender( String value )
    {
        this.houseOwnergender = value;
    }
    public String getHouseOwnergender()
    {
        return this.houseOwnergender;
    }

    //--- DB COLUMN : house_ownerCardNo ( varchar ) 
    public void setHouseOwnercardno( String value )
    {
        this.houseOwnercardno = value;
    }
    public String getHouseOwnercardno()
    {
        return this.houseOwnercardno;
    }

    //--- DB COLUMN : house_ownerAge ( tinyint ) 
    public void setHouseOwnerage( Byte value )
    {
        this.houseOwnerage = value;
    }
    public Byte getHouseOwnerage()
    {
        return this.houseOwnerage;
    }

    //--- DB COLUMN : house_colloate ( varchar ) 
    public void setHouseColloate( String value )
    {
        this.houseColloate = value;
    }
    public String getHouseColloate()
    {
        return this.houseColloate;
    }

    //--- DB COLUMN : house_colloateGender ( char ) 
    public void setHouseColloategender( String value )
    {
        this.houseColloategender = value;
    }
    public String getHouseColloategender()
    {
        return this.houseColloategender;
    }

    //--- DB COLUMN : house_colloaterCardNo ( varchar ) 
    public void setHouseColloatercardno( String value )
    {
        this.houseColloatercardno = value;
    }
    public String getHouseColloatercardno()
    {
        return this.houseColloatercardno;
    }

    //--- DB COLUMN : house_colloateAge ( tinyint ) 
    public void setHouseColloateage( Byte value )
    {
        this.houseColloateage = value;
    }
    public Byte getHouseColloateage()
    {
        return this.houseColloateage;
    }

    //--- DB COLUMN : house_address ( varchar ) 
    public void setHouseAddress( String value )
    {
        this.houseAddress = value;
    }
    public String getHouseAddress()
    {
        return this.houseAddress;
    }

    //--- DB COLUMN : house_square ( decimal ) 
    public void setHouseSquare( BigDecimal value )
    {
        this.houseSquare = value;
    }
    public BigDecimal getHouseSquare()
    {
        return this.houseSquare;
    }

    //--- DB COLUMN : house_value ( decimal ) 
    public void setHouseValue( BigDecimal value )
    {
        this.houseValue = value;
    }
    public BigDecimal getHouseValue()
    {
        return this.houseValue;
    }

    //--- DB COLUMN : house_lended ( tinyint ) 
    public void setHouseLended( Byte value )
    {
        this.houseLended = value;
    }
    public Byte getHouseLended()
    {
        return this.houseLended;
    }

    //--- DB COLUMN : house_lendedMoney ( decimal ) 
    public void setHouseLendedmoney( BigDecimal value )
    {
        this.houseLendedmoney = value;
    }
    public BigDecimal getHouseLendedmoney()
    {
        return this.houseLendedmoney;
    }


    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTLoan( TLoan value )
    {
        this.tLoan = value;
    }
    public TLoan getTLoan()
    {
        return this.tLoan;
    }



}
 



///////////////////

loanPid **
applyType **
houseCardno **
houseOwner **
houseOwnergender **
houseOwnercardno **
houseOwnerage **
houseColloate **
houseColloategender **
houseColloatercardno **
houseColloateage **
houseAddress **
houseSquare **
houseValue **
houseLended **
houseLendedmoney **

 "link.setter"     ----   setTLoan
  "link.linkType " ----   TLoan 
  "link.getter  "   ----   getTLoan
  
  
  
