//-----------------------------------------------------------
// This is a generated class. Avoid customizing code here !
// Generated by Telosys Tools Generator - version : 2.0.3
// Date : 17 ËÄÔÂ 2013 - Time 20:42:50
//-----------------------------------------------------------
// This class was generated by the standard template
// Template name    : vo_bean.vm
// Template author  : Stephane LABBE 
// Template version : 1.0.0 ( Aout 17 - 2011 ) 
//-----------------------------------------------------------

package com.hlj.tech.kdkj.customer.entities;

import java.io.Serializable;



import javax.persistence.*;


@Entity
@Table(name="t_loan_vechicle", catalog="bdf" )
public class TLoanVechicle implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="loan_vechicle_id", nullable=false)
    private Integer    loanVechicleId  ;
    
    @Column(name="loan_pid")
    private Integer    loanPid       ;
    
    @Column(name="vechicle_number", length=15)
    private String     vechicleNumber  ;
    
    @Column(name="vechicle_year")
    private Byte       vechicleYear  ;
    
    @Column(name="engine_number", length=25)
    private String     engineNumber  ;
    
    @Column(name="vechicle_miles")
    private Short      vechicleMiles  ;
    
    @Column(name="vechicle_modelType", length=100)
    private String     vechicleModeltype  ;
    
    @Column(name="apply_type", length=15)
    private String     applyType     ;
    

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToOne
    @JoinColumn(name="loan_pid", referencedColumnName="loan_id")
    private TLoan      tLoan       ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TLoanVechicle()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR ENTITY FIELDS
    //----------------------------------------------------------------------
    //--- DB PRIMARY KEY : loan_vechicle_id ( int ) 
    public void setLoanVechicleId( Integer value )
    {
        this.loanVechicleId = value;
    }
    public Integer getLoanVechicleId()
    {
        return this.loanVechicleId;
    }

    //--- DB COLUMN : loan_pid ( int ) 
    public void setLoanPid( Integer value )
    {
        this.loanPid = value;
    }
    public Integer getLoanPid()
    {
        return this.loanPid;
    }

    //--- DB COLUMN : vechicle_number ( varchar ) 
    public void setVechicleNumber( String value )
    {
        this.vechicleNumber = value;
    }
    public String getVechicleNumber()
    {
        return this.vechicleNumber;
    }

    //--- DB COLUMN : vechicle_year ( tinyint ) 
    public void setVechicleYear( Byte value )
    {
        this.vechicleYear = value;
    }
    public Byte getVechicleYear()
    {
        return this.vechicleYear;
    }

    //--- DB COLUMN : engine_number ( varchar ) 
    public void setEngineNumber( String value )
    {
        this.engineNumber = value;
    }
    public String getEngineNumber()
    {
        return this.engineNumber;
    }

    //--- DB COLUMN : vechicle_miles ( smallint ) 
    public void setVechicleMiles( Short value )
    {
        this.vechicleMiles = value;
    }
    public Short getVechicleMiles()
    {
        return this.vechicleMiles;
    }

    //--- DB COLUMN : vechicle_modelType ( varchar ) 
    public void setVechicleModeltype( String value )
    {
        this.vechicleModeltype = value;
    }
    public String getVechicleModeltype()
    {
        return this.vechicleModeltype;
    }

    //--- DB COLUMN : apply_type ( varchar ) 
    public void setApplyType( String value )
    {
        this.applyType = value;
    }
    public String getApplyType()
    {
        return this.applyType;
    }


    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTLoan( TLoan value )
    {
        this.tLoan = value;
    }
    public TLoan getTLoan()
    {
        return this.tLoan;
    }



}
 



///////////////////

loanPid **
vechicleNumber **
vechicleYear **
engineNumber **
vechicleMiles **
vechicleModeltype **
applyType **

 "link.setter"     ----   setTLoan
  "link.linkType " ----   TLoan 
  "link.getter  "   ----   getTLoan
  
  
  
