//-----------------------------------------------------------
// This is a generated class. Avoid customizing code here !
// Generated by Telosys Tools Generator - version : 2.0.3
// Date : 17 ËÄÔÂ 2013 - Time 20:42:50
//-----------------------------------------------------------
// This class was generated by the standard template
// Template name    : vo_bean.vm
// Template author  : Stephane LABBE 
// Template version : 1.0.0 ( Aout 17 - 2011 ) 
//-----------------------------------------------------------

package com.hlj.tech.kdkj.customer.entities;

import java.io.Serializable;

import java.util.Date;


import javax.persistence.*;


@Entity
@Table(name="t_loan_consult", catalog="bdf" )
public class TLoanConsult implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="loan_consultId", nullable=false)
    private Integer    loanConsultid  ;
    
    @Column(name="loan_pid")
    private Integer    loanPid       ;
    
    @Column(name="comment", length=500)
    private String     comment       ;
    
    @Column(name="consult_username", length=50)
    private String     consultUsername  ;
    
    @Temporal(TemporalType.DATE)
    @Column(name="update_date")
    private Date       updateDate    ;
    
    @Temporal(TemporalType.DATE)
    @Column(name="create_date")
    private Date       createDate    ;
    

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="loan_pid", referencedColumnName="loan_id", insertable=false, updatable=false)
    private TLoan      tLoan       ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TLoanConsult()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR ENTITY FIELDS
    //----------------------------------------------------------------------
    //--- DB PRIMARY KEY : loan_consultId ( int ) 
    public void setLoanConsultid( Integer value )
    {
        this.loanConsultid = value;
    }
    public Integer getLoanConsultid()
    {
        return this.loanConsultid;
    }

    //--- DB COLUMN : loan_pid ( int ) 
    public void setLoanPid( Integer value )
    {
        this.loanPid = value;
    }
    public Integer getLoanPid()
    {
        return this.loanPid;
    }

    //--- DB COLUMN : comment ( varchar ) 
    public void setComment( String value )
    {
        this.comment = value;
    }
    public String getComment()
    {
        return this.comment;
    }

    //--- DB COLUMN : consult_username ( varchar ) 
    public void setConsultUsername( String value )
    {
        this.consultUsername = value;
    }
    public String getConsultUsername()
    {
        return this.consultUsername;
    }

    //--- DB COLUMN : update_date ( date ) 
    public void setUpdateDate( Date value )
    {
        this.updateDate = value;
    }
    public Date getUpdateDate()
    {
        return this.updateDate;
    }

    //--- DB COLUMN : create_date ( date ) 
    public void setCreateDate( Date value )
    {
        this.createDate = value;
    }
    public Date getCreateDate()
    {
        return this.createDate;
    }


    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTLoan( TLoan value )
    {
        this.tLoan = value;
    }
    public TLoan getTLoan()
    {
        return this.tLoan;
    }



}
 



///////////////////

loanPid **
comment **
consultUsername **
updateDate **
createDate **

 "link.setter"     ----   setTLoan
  "link.linkType " ----   TLoan 
  "link.getter  "   ----   getTLoan
  
  
  
