//-----------------------------------------------------------
// This is a generated class. Avoid customizing code here !
// Generated by Telosys Tools Generator - version : 2.0.3
// Date : 17 ËÄÔÂ 2013 - Time 20:42:50
//-----------------------------------------------------------
// This class was generated by the standard template
// Template name    : vo_bean.vm
// Template author  : Stephane LABBE 
// Template version : 1.0.0 ( Aout 17 - 2011 ) 
//-----------------------------------------------------------

package com.hlj.tech.kdkj.customer.entities;

import java.io.Serializable;

import java.math.BigDecimal;
import java.util.Date;


import java.util.List;
import javax.persistence.*;


@Entity
@Table(name="t_loan", catalog="bdf" )
public class TLoan implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="loan_id", nullable=false)
    private Integer    loanId        ;
    
    @Column(name="customer_pid")
    private Integer    customerPid   ;
    
    @Column(name="userName_", length=50)
    private String     username      ;
    
    @Column(name="loan_limit")
    private BigDecimal loanLimit     ;
    
    @Column(name="loan_month")
    private Integer    loanMonth     ;
    
    @Column(name="loan_returnType", length=20)
    private String     loanReturntype  ;
    
    @Column(name="loan_usage", length=200)
    private String     loanUsage     ;
    
    @Temporal(TemporalType.DATE)
    @Column(name="loan_openTime")
    private Date       loanOpentime  ;
    
    @Column(name="bank_account", length=50)
    private String     bankAccount   ;
    
    @Column(name="bank_accountNo", length=20)
    private String     bankAccountno  ;
    
    @Column(name="bank_openName", length=20)
    private String     bankOpenname  ;
    
    @Column(name="bank_type", length=30)
    private String     bankType      ;
    
    @Column(name="loan_bigType", length=20)
    private String     loanBigtype   ;
    
    @Column(name="loan_smallType", length=20)
    private String     loanSmalltype  ;
    
    @Column(name="state", length=20)
    private String     state         ;
    
    @Column(name="success")
    private Byte       success       ;
    
    @Column(name="success_state", length=30)
    private String     successState  ;
    
    @Temporal(TemporalType.DATE)
    @Column(name="create_date")
    private Date       createDate    ;
    
    @Temporal(TemporalType.DATE)
    @Column(name="update_date")
    private Date       updateDate    ;
    
    @Column(name="multi_borrower")
    private Byte       multiBorrower  ;
    
    @Column(name="loan_genNumber", length=20)
    private String     loanGennumber  ;
    

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToOne(mappedBy="tLoan", targetEntity=TLoanHouse.class)
    private TLoanHouse TLoanHouse  ;
    
    @OneToMany(mappedBy="tLoan", targetEntity=TSpousefriend.class)
    private List<TSpousefriend> listOfTSpousefriend;
    
    @OneToMany(mappedBy="tLoan", targetEntity=TLoanConsult.class)
    private List<TLoanConsult> listOfTLoanConsult;
    
    @ManyToOne
    @JoinColumn(name="customer_pid", referencedColumnName="customer_id", insertable=false, updatable=false)
    private TCustomer  tCustomer   ;
    
    @OneToOne(mappedBy="tLoan", targetEntity=TLoanVechicle.class)
    private TLoanVechicle TLoanVechicle;
    
    @OneToOne(mappedBy="tLoan", targetEntity=TLoanBoss.class)
    private TLoanBoss  TLoanBoss   ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TLoan()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR ENTITY FIELDS
    //----------------------------------------------------------------------
    //--- DB PRIMARY KEY : loan_id ( int ) 
    public void setLoanId( Integer value )
    {
        this.loanId = value;
    }
    public Integer getLoanId()
    {
        return this.loanId;
    }

    //--- DB COLUMN : customer_pid ( int ) 
    public void setCustomerPid( Integer value )
    {
        this.customerPid = value;
    }
    public Integer getCustomerPid()
    {
        return this.customerPid;
    }

    //--- DB COLUMN : userName_ ( varchar ) 
    public void setUsername( String value )
    {
        this.username = value;
    }
    public String getUsername()
    {
        return this.username;
    }

    //--- DB COLUMN : loan_limit ( decimal ) 
    public void setLoanLimit( BigDecimal value )
    {
        this.loanLimit = value;
    }
    public BigDecimal getLoanLimit()
    {
        return this.loanLimit;
    }

    //--- DB COLUMN : loan_month ( int ) 
    public void setLoanMonth( Integer value )
    {
        this.loanMonth = value;
    }
    public Integer getLoanMonth()
    {
        return this.loanMonth;
    }

    //--- DB COLUMN : loan_returnType ( varchar ) 
    public void setLoanReturntype( String value )
    {
        this.loanReturntype = value;
    }
    public String getLoanReturntype()
    {
        return this.loanReturntype;
    }

    //--- DB COLUMN : loan_usage ( varchar ) 
    public void setLoanUsage( String value )
    {
        this.loanUsage = value;
    }
    public String getLoanUsage()
    {
        return this.loanUsage;
    }

    //--- DB COLUMN : loan_openTime ( date ) 
    public void setLoanOpentime( Date value )
    {
        this.loanOpentime = value;
    }
    public Date getLoanOpentime()
    {
        return this.loanOpentime;
    }

    //--- DB COLUMN : bank_account ( varchar ) 
    public void setBankAccount( String value )
    {
        this.bankAccount = value;
    }
    public String getBankAccount()
    {
        return this.bankAccount;
    }

    //--- DB COLUMN : bank_accountNo ( varchar ) 
    public void setBankAccountno( String value )
    {
        this.bankAccountno = value;
    }
    public String getBankAccountno()
    {
        return this.bankAccountno;
    }

    //--- DB COLUMN : bank_openName ( varchar ) 
    public void setBankOpenname( String value )
    {
        this.bankOpenname = value;
    }
    public String getBankOpenname()
    {
        return this.bankOpenname;
    }

    //--- DB COLUMN : bank_type ( varchar ) 
    public void setBankType( String value )
    {
        this.bankType = value;
    }
    public String getBankType()
    {
        return this.bankType;
    }

    //--- DB COLUMN : loan_bigType ( varchar ) 
    public void setLoanBigtype( String value )
    {
        this.loanBigtype = value;
    }
    public String getLoanBigtype()
    {
        return this.loanBigtype;
    }

    //--- DB COLUMN : loan_smallType ( varchar ) 
    public void setLoanSmalltype( String value )
    {
        this.loanSmalltype = value;
    }
    public String getLoanSmalltype()
    {
        return this.loanSmalltype;
    }

    //--- DB COLUMN : state ( varchar ) 
    public void setState( String value )
    {
        this.state = value;
    }
    public String getState()
    {
        return this.state;
    }

    //--- DB COLUMN : success ( tinyint ) 
    public void setSuccess( Byte value )
    {
        this.success = value;
    }
    public Byte getSuccess()
    {
        return this.success;
    }

    //--- DB COLUMN : success_state ( varchar ) 
    public void setSuccessState( String value )
    {
        this.successState = value;
    }
    public String getSuccessState()
    {
        return this.successState;
    }

    //--- DB COLUMN : create_date ( date ) 
    public void setCreateDate( Date value )
    {
        this.createDate = value;
    }
    public Date getCreateDate()
    {
        return this.createDate;
    }

    //--- DB COLUMN : update_date ( date ) 
    public void setUpdateDate( Date value )
    {
        this.updateDate = value;
    }
    public Date getUpdateDate()
    {
        return this.updateDate;
    }

    //--- DB COLUMN : multi_borrower ( tinyint ) 
    public void setMultiBorrower( Byte value )
    {
        this.multiBorrower = value;
    }
    public Byte getMultiBorrower()
    {
        return this.multiBorrower;
    }

    //--- DB COLUMN : loan_genNumber ( varchar ) 
    public void setLoanGennumber( String value )
    {
        this.loanGennumber = value;
    }
    public String getLoanGennumber()
    {
        return this.loanGennumber;
    }


    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTLoanHouse( TLoanHouse value )
    {
        this.TLoanHouse = value;
    }
    public TLoanHouse getTLoanHouse()
    {
        return this.TLoanHouse;
    }

    public void setListOfTSpousefriend( List<TSpousefriend> value )
    {
        this.listOfTSpousefriend = value;
    }
    public List<TSpousefriend> getListOfTSpousefriend()
    {
        return this.listOfTSpousefriend;
    }

    public void setListOfTLoanConsult( List<TLoanConsult> value )
    {
        this.listOfTLoanConsult = value;
    }
    public List<TLoanConsult> getListOfTLoanConsult()
    {
        return this.listOfTLoanConsult;
    }

    public void setTCustomer( TCustomer value )
    {
        this.tCustomer = value;
    }
    public TCustomer getTCustomer()
    {
        return this.tCustomer;
    }

    public void setTLoanVechicle( TLoanVechicle value )
    {
        this.TLoanVechicle = value;
    }
    public TLoanVechicle getTLoanVechicle()
    {
        return this.TLoanVechicle;
    }

    public void setTLoanBoss( TLoanBoss value )
    {
        this.TLoanBoss = value;
    }
    public TLoanBoss getTLoanBoss()
    {
        return this.TLoanBoss;
    }



}
 



///////////////////

customerPid **
username **
loanLimit **
loanMonth **
loanReturntype **
loanUsage **
loanOpentime **
bankAccount **
bankAccountno **
bankOpenname **
bankType **
loanBigtype **
loanSmalltype **
state **
success **
successState **
createDate **
updateDate **
multiBorrower **
loanGennumber **

 "link.setter"     ----   setTLoanHouse
  "link.linkType " ----   TLoanHouse 
  "link.getter  "   ----   getTLoanHouse
  
  
  
 "link.setter"     ----   setListOfTSpousefriend
  "link.linkType " ----   List<TSpousefriend> 
  "link.getter  "   ----   getListOfTSpousefriend
  
  
  
 "link.setter"     ----   setListOfTLoanConsult
  "link.linkType " ----   List<TLoanConsult> 
  "link.getter  "   ----   getListOfTLoanConsult
  
  
  
 "link.setter"     ----   setTCustomer
  "link.linkType " ----   TCustomer 
  "link.getter  "   ----   getTCustomer
  
  
  
 "link.setter"     ----   setTLoanVechicle
  "link.linkType " ----   TLoanVechicle 
  "link.getter  "   ----   getTLoanVechicle
  
  
  
 "link.setter"     ----   setTLoanBoss
  "link.linkType " ----   TLoanBoss 
  "link.getter  "   ----   getTLoanBoss
  
  
  
