//-----------------------------------------------------------
// This is a generated class. Avoid customizing code here !
// Generated by Telosys Tools Generator - version : 2.0.3
// Date : 17 ËÄÔÂ 2013 - Time 20:42:50
//-----------------------------------------------------------
// This class was generated by the standard template
// Template name    : vo_bean.vm
// Template author  : Stephane LABBE 
// Template version : 1.0.0 ( Aout 17 - 2011 ) 
//-----------------------------------------------------------

package com.hlj.tech.kdkj.customer.entities;

import java.io.Serializable;

import java.math.BigDecimal;


import javax.persistence.*;


@Entity
@Table(name="t_loan_boss", catalog="bdf" )
public class TLoanBoss implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="loan_boss_id", nullable=false)
    private Integer    loanBossId    ;
    
    @Column(name="loan_pid")
    private Integer    loanPid       ;
    
    @Column(name="company_years")
    private Byte       companyYears  ;
    
    @Column(name="company_square")
    private BigDecimal companySquare  ;
    
    @Column(name="company_openMoney")
    private BigDecimal companyOpenmoney  ;
    

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToOne
    @JoinColumn(name="loan_pid", referencedColumnName="loan_id")
    private TLoan      tLoan       ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TLoanBoss()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR ENTITY FIELDS
    //----------------------------------------------------------------------
    //--- DB PRIMARY KEY : loan_boss_id ( int ) 
    public void setLoanBossId( Integer value )
    {
        this.loanBossId = value;
    }
    public Integer getLoanBossId()
    {
        return this.loanBossId;
    }

    //--- DB COLUMN : loan_pid ( int ) 
    public void setLoanPid( Integer value )
    {
        this.loanPid = value;
    }
    public Integer getLoanPid()
    {
        return this.loanPid;
    }

    //--- DB COLUMN : company_years ( tinyint ) 
    public void setCompanyYears( Byte value )
    {
        this.companyYears = value;
    }
    public Byte getCompanyYears()
    {
        return this.companyYears;
    }

    //--- DB COLUMN : company_square ( decimal ) 
    public void setCompanySquare( BigDecimal value )
    {
        this.companySquare = value;
    }
    public BigDecimal getCompanySquare()
    {
        return this.companySquare;
    }

    //--- DB COLUMN : company_openMoney ( decimal ) 
    public void setCompanyOpenmoney( BigDecimal value )
    {
        this.companyOpenmoney = value;
    }
    public BigDecimal getCompanyOpenmoney()
    {
        return this.companyOpenmoney;
    }


    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTLoan( TLoan value )
    {
        this.tLoan = value;
    }
    public TLoan getTLoan()
    {
        return this.tLoan;
    }



}
 



///////////////////

loanPid **
companyYears **
companySquare **
companyOpenmoney **

 "link.setter"     ----   setTLoan
  "link.linkType " ----   TLoan 
  "link.getter  "   ----   getTLoan
  
  
  
