//-----------------------------------------------------------
// This is a generated class. Avoid customizing code here !
// Generated by Telosys Tools Generator - version : 2.0.3
// Date : 17 ËÄÔÂ 2013 - Time 20:42:50
//-----------------------------------------------------------
// This class was generated by the standard template
// Template name    : vo_bean.vm
// Template author  : Stephane LABBE 
// Template version : 1.0.0 ( Aout 17 - 2011 ) 
//-----------------------------------------------------------

package com.hlj.tech.kdkj.customer.entities;

import java.io.Serializable;

import java.util.Date;


import javax.persistence.*;


@Entity
@Table(name="t_spousefriend", catalog="bdf" )
public class TSpousefriend implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="spouse_friendId", nullable=false)
    private Integer    spouseFriendid  ;
    
    @Column(name="customer_pid")
    private Integer    customerPid   ;
    
    @Column(name="loan_pid")
    private Integer    loanPid       ;
    
    @Column(name="name", length=50)
    private String     name          ;
    
    @Column(name="gender", length=10)
    private String     gender        ;
    
    @Column(name="cardNo", length=30)
    private String     cardno        ;
    
    @Column(name="card_type", length=10)
    private String     cardType      ;
    
    @Column(name="age")
    private Short      age           ;
    
    @Column(name="address", length=50)
    private String     address       ;
    
    @Column(name="telephone", length=15)
    private String     telephone     ;
    
    @Column(name="home_phone", length=15)
    private String     homePhone     ;
    
    @Column(name="office_company", length=100)
    private String     officeCompany  ;
    
    @Column(name="office_telephone", length=20)
    private String     officeTelephone  ;
    
    @Column(name="depart_typename", length=30)
    private String     departTypename  ;
    
    @Column(name="office_address", length=100)
    private String     officeAddress  ;
    
    @Column(name="year_salary")
    private Integer    yearSalary    ;
    
    @Column(name="office_year")
    private Integer    officeYear    ;
    
    @Temporal(TemporalType.DATE)
    @Column(name="birthday")
    private Date       birthday      ;
    
    @Column(name="relation_type", length=10)
    private String     relationType  ;
    
    @Column(name="relation_typeName", length=30)
    private String     relationTypename  ;
    

    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="customer_pid", referencedColumnName="customer_id", insertable=false, updatable=false)
    private TCustomer  tCustomer   ;
    
    @ManyToOne
    @JoinColumn(name="loan_pid", referencedColumnName="loan_id", insertable=false, updatable=false)
    private TLoan      tLoan       ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public TSpousefriend()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR ENTITY FIELDS
    //----------------------------------------------------------------------
    //--- DB PRIMARY KEY : spouse_friendId ( int ) 
    public void setSpouseFriendid( Integer value )
    {
        this.spouseFriendid = value;
    }
    public Integer getSpouseFriendid()
    {
        return this.spouseFriendid;
    }

    //--- DB COLUMN : customer_pid ( int ) 
    public void setCustomerPid( Integer value )
    {
        this.customerPid = value;
    }
    public Integer getCustomerPid()
    {
        return this.customerPid;
    }

    //--- DB COLUMN : loan_pid ( int ) 
    public void setLoanPid( Integer value )
    {
        this.loanPid = value;
    }
    public Integer getLoanPid()
    {
        return this.loanPid;
    }

    //--- DB COLUMN : name ( varchar ) 
    public void setName( String value )
    {
        this.name = value;
    }
    public String getName()
    {
        return this.name;
    }

    //--- DB COLUMN : gender ( varchar ) 
    public void setGender( String value )
    {
        this.gender = value;
    }
    public String getGender()
    {
        return this.gender;
    }

    //--- DB COLUMN : cardNo ( varchar ) 
    public void setCardno( String value )
    {
        this.cardno = value;
    }
    public String getCardno()
    {
        return this.cardno;
    }

    //--- DB COLUMN : card_type ( varchar ) 
    public void setCardType( String value )
    {
        this.cardType = value;
    }
    public String getCardType()
    {
        return this.cardType;
    }

    //--- DB COLUMN : age ( smallint ) 
    public void setAge( Short value )
    {
        this.age = value;
    }
    public Short getAge()
    {
        return this.age;
    }

    //--- DB COLUMN : address ( varchar ) 
    public void setAddress( String value )
    {
        this.address = value;
    }
    public String getAddress()
    {
        return this.address;
    }

    //--- DB COLUMN : telephone ( varchar ) 
    public void setTelephone( String value )
    {
        this.telephone = value;
    }
    public String getTelephone()
    {
        return this.telephone;
    }

    //--- DB COLUMN : home_phone ( varchar ) 
    public void setHomePhone( String value )
    {
        this.homePhone = value;
    }
    public String getHomePhone()
    {
        return this.homePhone;
    }

    //--- DB COLUMN : office_company ( varchar ) 
    public void setOfficeCompany( String value )
    {
        this.officeCompany = value;
    }
    public String getOfficeCompany()
    {
        return this.officeCompany;
    }

    //--- DB COLUMN : office_telephone ( varchar ) 
    public void setOfficeTelephone( String value )
    {
        this.officeTelephone = value;
    }
    public String getOfficeTelephone()
    {
        return this.officeTelephone;
    }

    //--- DB COLUMN : depart_typename ( varchar ) 
    public void setDepartTypename( String value )
    {
        this.departTypename = value;
    }
    public String getDepartTypename()
    {
        return this.departTypename;
    }

    //--- DB COLUMN : office_address ( varchar ) 
    public void setOfficeAddress( String value )
    {
        this.officeAddress = value;
    }
    public String getOfficeAddress()
    {
        return this.officeAddress;
    }

    //--- DB COLUMN : year_salary ( int ) 
    public void setYearSalary( Integer value )
    {
        this.yearSalary = value;
    }
    public Integer getYearSalary()
    {
        return this.yearSalary;
    }

    //--- DB COLUMN : office_year ( int ) 
    public void setOfficeYear( Integer value )
    {
        this.officeYear = value;
    }
    public Integer getOfficeYear()
    {
        return this.officeYear;
    }

    //--- DB COLUMN : birthday ( date ) 
    public void setBirthday( Date value )
    {
        this.birthday = value;
    }
    public Date getBirthday()
    {
        return this.birthday;
    }

    //--- DB COLUMN : relation_type ( varchar ) 
    public void setRelationType( String value )
    {
        this.relationType = value;
    }
    public String getRelationType()
    {
        return this.relationType;
    }

    //--- DB COLUMN : relation_typeName ( varchar ) 
    public void setRelationTypename( String value )
    {
        this.relationTypename = value;
    }
    public String getRelationTypename()
    {
        return this.relationTypename;
    }


    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setTCustomer( TCustomer value )
    {
        this.tCustomer = value;
    }
    public TCustomer getTCustomer()
    {
        return this.tCustomer;
    }

    public void setTLoan( TLoan value )
    {
        this.tLoan = value;
    }
    public TLoan getTLoan()
    {
        return this.tLoan;
    }



}
 



///////////////////

customerPid **
loanPid **
name **
gender **
cardno **
cardType **
age **
address **
telephone **
homePhone **
officeCompany **
officeTelephone **
departTypename **
officeAddress **
yearSalary **
officeYear **
birthday **
relationType **
relationTypename **

 "link.setter"     ----   setTCustomer
  "link.linkType " ----   TCustomer 
  "link.getter  "   ----   getTCustomer
  
  
  
 "link.setter"     ----   setTLoan
  "link.linkType " ----   TLoan 
  "link.getter  "   ----   getTLoan
  
  
  
