/*
 * Java bean class for entity table t_city 
 * Created on 13 ËÄÔÂ 2013 ( Time 17:11:27 )
 * Generated by Telosys Tools Generator ( version 2.0.3 )
 */

package com.hlj.tech.kdkj.auto.entities ;

import java.io.Serializable;
import java.util.List;


/**
 * Entity bean for table "t_city"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TCity implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Short      id           ; // Primary Key

    private Short      provinceId   ;
    private String     name         ;
    private TProvince  tProvince   ;
    /**
     * Default constructor
     */
    public TCity()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "id" ( type "smallint", ) 
     * @param id
     */
	public void setId( Short id )
    {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "id" ( type "smallint", ) 
     * @return the field value
     */
	public Short getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : province_id ( smallint ) 
    /**
     * Set the "provinceId" field value
     * This field is mapped on the database column "province_id" ( type "smallint" ) 
     * @param provinceId
     */
    public void setProvinceId( Short provinceId )
    {
        this.provinceId = provinceId;
    }
    /**
     * Get the "provinceId" field value
     * This field is mapped on the database column "province_id" ( type "smallint" ) 
     * @return the field value
     */
    public Short getProvinceId()
    {
        return this.provinceId;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    /**
     * Set the "name" field value
     * This field is mapped on the database column "name" ( type "varchar" ) 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    }
    /**
     * Get the "name" field value
     * This field is mapped on the database column "name" ( type "varchar" ) 
     * @return the field value
     */
    public String getName()
    {
        return this.name;
    }

    public void setTProvince( TProvince tProvince )
    {
        this.tProvince = tProvince;
    }
    public TProvince getTProvince()
    {
        return this.tProvince;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(id); 
        sb.append("|"); 
        sb.append(provinceId); 
        sb.append( "|" ); 
        sb.append(name); 
        return sb.toString();
    }

}
