/*
 * Java bean class for entity table t_province 
 * Created on 13 ËÄÔÂ 2013 ( Time 17:11:27 )
 * Generated by Telosys Tools Generator ( version 2.0.3 )
 */

package com.hlj.tech.kdkj.auto.entities ;

import java.io.Serializable;
import java.util.List;


/**
 * Entity bean for table "t_province"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TProvince implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Short      id           ; // Primary Key

    private String     code         ;
    private String     name         ;
    private List<TCity> listOfTCity ;
    /**
     * Default constructor
     */
    public TProvince()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "id" field value
     * This field is mapped on the database column "id" ( type "smallint", ) 
     * @param id
     */
	public void setId( Short id )
    {
        this.id = id ;
    }
    /**
     * Get the "id" field value
     * This field is mapped on the database column "id" ( type "smallint", ) 
     * @return the field value
     */
	public Short getId()
    {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : code ( varchar ) 
    /**
     * Set the "code" field value
     * This field is mapped on the database column "code" ( type "varchar" ) 
     * @param code
     */
    public void setCode( String code )
    {
        this.code = code;
    }
    /**
     * Get the "code" field value
     * This field is mapped on the database column "code" ( type "varchar" ) 
     * @return the field value
     */
    public String getCode()
    {
        return this.code;
    }

    //--- DATABASE MAPPING : name ( varchar ) 
    /**
     * Set the "name" field value
     * This field is mapped on the database column "name" ( type "varchar" ) 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    }
    /**
     * Get the "name" field value
     * This field is mapped on the database column "name" ( type "varchar" ) 
     * @return the field value
     */
    public String getName()
    {
        return this.name;
    }

    public void setListOfTCity( List<TCity> listOfTCity )
    {
        this.listOfTCity = listOfTCity;
    }
    public List<TCity> getListOfTCity()
    {
        return this.listOfTCity;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(id); 
        sb.append("|"); 
        sb.append(code); 
        sb.append( "|" ); 
        sb.append(name); 
        return sb.toString();
    }

}
