/*
 * Java bean class for entity table t_student 
 * Created on 14 ËÄÔÂ 2013 ( Time 08:33:42 )
 * Generated by Telosys Tools Generator ( version 2.0.3 )
 */

package com.hlj.tech.kdkj.auto.entities ;

import java.io.Serializable;
import java.util.List;

import java.util.Date;

/**
 * Entity bean for table "t_student"
 * 
 * @author Telosys Tools Generator
 *
 */
public class TStudent implements Serializable
{
    private static final long serialVersionUID = 1L;

    private Integer    studentId    ; // Primary Key

    private String     name         ;
    private String     email        ;
    private Date       birthday     ;
    /**
     * Default constructor
     */
    public TStudent()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------
    /**
     * Set the "studentId" field value
     * This field is mapped on the database column "student_id" ( type "int", ) 
     * @param studentId
     */
	public void setStudentId( Integer studentId )
    {
        this.studentId = studentId ;
    }
    /**
     * Get the "studentId" field value
     * This field is mapped on the database column "student_id" ( type "int", ) 
     * @return the field value
     */
	public Integer getStudentId()
    {
        return this.studentId;
    }

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : name ( varchar ) 
    /**
     * Set the "name" field value
     * This field is mapped on the database column "name" ( type "varchar" ) 
     * @param name
     */
    public void setName( String name )
    {
        this.name = name;
    }
    /**
     * Get the "name" field value
     * This field is mapped on the database column "name" ( type "varchar" ) 
     * @return the field value
     */
    public String getName()
    {
        return this.name;
    }

    //--- DATABASE MAPPING : email ( varchar ) 
    /**
     * Set the "email" field value
     * This field is mapped on the database column "email" ( type "varchar" ) 
     * @param email
     */
    public void setEmail( String email )
    {
        this.email = email;
    }
    /**
     * Get the "email" field value
     * This field is mapped on the database column "email" ( type "varchar" ) 
     * @return the field value
     */
    public String getEmail()
    {
        return this.email;
    }

    //--- DATABASE MAPPING : birthday ( date ) 
    /**
     * Set the "birthday" field value
     * This field is mapped on the database column "birthday" ( type "date" ) 
     * @param birthday
     */
    public void setBirthday( Date birthday )
    {
        this.birthday = birthday;
    }
    /**
     * Get the "birthday" field value
     * This field is mapped on the database column "birthday" ( type "date" ) 
     * @return the field value
     */
    public Date getBirthday()
    {
        return this.birthday;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(studentId); 
        sb.append("|"); 
        sb.append(name); 
        sb.append( "|" ); 
        sb.append(email); 
        sb.append( "|" ); 
        sb.append(birthday); 
        return sb.toString();
    }

}
